import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";
const read=(path:string)=>readFileSync(path,"utf8");

test("canonical app visual system separates app titles from marketing hero",()=>{const css=read("app/globals.css");assert.match(css,/--control-height:44px/);assert.match(css,/\.pageTitle h1\{[^}]*font-size:clamp\(30px,4vw,42px\)/);assert.doesNotMatch(css,/\.hero h1,\s*\.pageTitle h1/);assert.match(read("app/home.module.css"),/matchCardBody[\s\S]*textLink[\s\S]*margin-top:\s*auto/);});

test("Settings restores independent username changes",()=>{const form=read("app/settings/ProfileSettingsForm.tsx");assert.match(form,/Change username/);assert.match(form,/can be changed once every 30 days/);assert.match(form,/previous username stays reserved to you for 30 days/i);assert.doesNotMatch(form,/>Locked</);assert.match(read("app/settings/actions.ts"),/get_username_change_status/);});

test("FITuition quick view has all three evidence states",()=>{const panel=read("app/outfits/[id]/TaggedItemsPanel.tsx");assert.match(panel,/Recommended size/);assert.match(panel,/I’m not confident enough to recommend a size yet/);assert.match(panel,/I don’t have Fit Reports from people close enough to your measurements yet/);assert.match(panel,/See Relevant Fit Reports/);assert.match(panel,/Notify me when Fit Reports from people close to my measurements are posted/);assert.match(panel,/View Detailed Garment Report/);assert.match(read("lib/quick-fit-evidence.ts"),/QUICK_VIEW_STRONG_MATCH_THRESHOLD\s*=\s*85/);});

test("Outfit gallery has one owning stylesheet and comments are not duplicated",()=>{const gallery=read("app/outfits/[id]/OutfitGallery.tsx");assert.doesNotMatch(gallery,/outfitInteraction\.module\.css|outfitPolish\.module\.css/);assert.equal(existsSync("app/outfits/[id]/outfitInteraction.module.css"),false);assert.equal(existsSync("app/outfits/[id]/outfitPolish.module.css"),false);assert.doesNotMatch(read("app/outfits/[id]/outfitDetail.module.css"),/commentsSheet|commentsOverlay|commentPreviewList/);assert.match(read("app/outfits/[id]/CommentThread.module.css"),/\.sheet/);});

test("measurement help and garment inspection use the canonical expandable image viewer",()=>{const viewer=read("components/GlobalDialogImageViewer.tsx");const layout=read("app/layout.tsx");const picker=read("app/outfits/new/outfitPicker.module.css");assert.match(viewer,/SwipeDismissImageLightbox/);assert.match(viewer,/closest\("img,svg"\)/);assert.match(layout,/GlobalDialogImageViewer/);assert.match(read("app/onboarding/MeasurementHelp.module.css"),/cursor:zoom-in/);assert.match(picker,/No garment photo yet/);assert.match(picker,/role="dialog"/);assert.match(picker,/place-items:center/);assert.match(picker,/cursor:zoom-in/);});

test("advanced Fit Profile measurements are prioritized and grouped",()=>{const form=read("app/onboarding/FitProfileForm.tsx");assert.match(form,/HIGH_VALUE_ADVANCED_KEYS/);assert.match(form,/Most useful additional measurements/);assert.match(form,/Additional measurements/);assert.match(form,/Upper body/);assert.match(form,/Lower body/);assert.match(form,/Feet/);assert.match(form,/regionGroups/);});

test("Outfit occasions are alphabetical and style chips navigate directly to filtered Explore",()=>{const taxonomy=read("lib/outfit-taxonomy.ts");const tabs=read("app/outfits/[id]/OutfitTabs.tsx");const explore=read("app/explore/page.tsx");assert.ok(taxonomy.indexOf('label: "Beach"')<taxonomy.indexOf('label: "Brunch"'));assert.ok(taxonomy.indexOf('label: "Brunch"')<taxonomy.indexOf('label: "Business Casual"'));assert.match(tabs,/window\.location\.assign\(`\/explore\?/);assert.match(tabs,/params\.set\("occasion"/);assert.match(tabs,/params\.set\("style"/);assert.match(explore,/outfit_occasions/);assert.match(explore,/outfit_style_tags/);assert.match(explore,/Back to Outfit/);});

test("garment report panel opens upward inside the quick view",()=>{assert.match(read("app/outfits/[id]/TaggedItemsPanel.module.css"),/bottom:48px!important/);assert.match(read("app/outfits/[id]/TaggedItemsPanel.module.css"),/top:auto!important/);});
