"use client";

import { useMemo, useState } from "react";
import styles from "./browsePreview.module.css";

type Mode="garments"|"outfits";
type Scope="matches"|"all";
type SearchTab="all"|"garments"|"outfits"|"people";
type Person={id:string;name:string;username:string;overall:number;tops:number;bottoms:number;fitTwins:number;styleLikes:number};
type Garment={id:string;brand:string;name:string;category:string;type:string;style:string;color:string;wearerId:string;wearer:string;size:string;fit:string;match:number;overall:number;likes:number;age:number;saved:boolean;notify:boolean};
type Outfit={id:string;creatorId:string;creator:string;caption:string;type:string;season:string;match:number;likes:number;age:number;saved:boolean;garments:string[]};
type Overlay={kind:"garment";id:string}|{kind:"outfit";id:string}|{kind:"person";id:string}|null;

const people:Person[]=[
{id:"p1",name:"Tina Carter",username:"tinac",overall:94,tops:96,bottoms:91,fitTwins:2400,styleLikes:18700},
{id:"p2",name:"Maya Reed",username:"mayareed",overall:91,tops:88,bottoms:95,fitTwins:860,styleLikes:6420},
{id:"p3",name:"Alex Jordan",username:"alexj",overall:87,tops:90,bottoms:84,fitTwins:1310,styleLikes:9100},
{id:"p4",name:"Sam Brooks",username:"samb",overall:82,tops:85,bottoms:79,fitTwins:420,styleLikes:2880},
{id:"p5",name:"Jordan Lee",username:"jlee",overall:78,tops:77,bottoms:81,fitTwins:205,styleLikes:1330},
];

const baseGarments=[
["Levi's","501 Original","Bottoms","Jeans","Straight","Dark Blue"],
["Madewell","Perfect Vintage Jean","Bottoms","Jeans","High-Waisted","Light Blue"],
["Everlane","Organic Cotton Box-Cut Tee","Tops","T-Shirts","Crop","White"],
["Aritzia","Contour Crew Bodysuit","Dresses & One-Pieces","Bodysuits","Fitted","Black"],
["Nike","One High-Waisted Leggings","Activewear","Bottoms","Leggings","Black"],
["J.Crew","Garçon Classic Shirt","Tops","Shirts & Blouses","Oversized","Blue"],
["Lululemon","Define Jacket","Activewear","Jackets & Layers","Zip-Up","Black"],
["Abercrombie","Sloane Tailored Pant","Bottoms","Pants","Dress Pants","Brown/Tan"],
["Free People","Hot Shot Onesie","Dresses & One-Pieces","Jumpsuits","Relaxed","Green"],
["Reformation","Tagliatelle Linen Dress","Dresses & One-Pieces","Dresses","Midi","White"],
] as const;

const garments:Garment[]=Array.from({length:40},(_,i)=>{const b=baseGarments[i%baseGarments.length];const p=people[i%people.length];return{id:`g${i+1}`,brand:b[0],name:b[1],category:b[2],type:b[3],style:b[4],color:b[5],wearerId:p.id,wearer:p.name,size:["XS","S","M","L","XL","28","30","32"][i%8],fit:["Just Right","Snug","Relaxed","Just Right","Too Big"][i%5],match:99-(i%25),overall:p.overall,likes:36+((i*37)%520),age:i%31,saved:i%9===0,notify:i%13===0};});

const outfits:Outfit[]=Array.from({length:30},(_,i)=>{const p=people[i%people.length];return{id:`o${i+1}`,creatorId:p.id,creator:p.name,caption:["Easy everyday layers","Workday neutrals","Dinner out","Weekend travel fit","Summer day look"][i%5],type:["Casual","Work","Going Out","Travel","Active"][i%5],season:["Year-Round","Fall","Summer","Spring","Winter"][i%5],match:97-(i%23),likes:18+((i*29)%410),age:i%24,saved:i%8===0,garments:[garments[i%garments.length].id,garments[(i+3)%garments.length].id]};});

const categories=["All","Tops","Bottoms","Dresses & One-Pieces","Outerwear","Activewear","Swimwear","Lingerie","Shoes"];
const outfitTypes=["All","Casual","Work","Going Out","Formal","Active","Travel","Lounge","Swimwear","Lingerie"];
const seasons=["All","Spring","Summer","Fall","Winter","Year-Round"];
const fitTiers=(score:number)=>score>=90?0:score>=85?1:score>=80?2:score>=75?3:4;
const hot=(likes:number,age:number)=>Math.log1p(likes)*.72+(1/(1+age/14))*2.8;

export default function BrowsePreview(){
 const[mode,setMode]=useState<Mode>("garments"),[gScope,setGScope]=useState<Scope>("matches"),[oScope,setOScope]=useState<Scope>("matches");
 const[gSort,setGSort]=useState("best"),[oSort,setOSort]=useState("best"),[category,setCategory]=useState("All"),[type,setType]=useState("All"),[style,setStyle]=useState("All"),[brand,setBrand]=useState("All"),[model,setModel]=useState("All"),[color,setColor]=useState("All");
 const[oType,setOType]=useState("All"),[season,setSeason]=useState("All"),[limit,setLimit]=useState(24),[query,setQuery]=useState(""),[searchOpen,setSearchOpen]=useState(false),[searchTab,setSearchTab]=useState<SearchTab>("all");
 const[overlay,setOverlay]=useState<Overlay>(null),[stack,setStack]=useState<Overlay[]>([]),[likedGarments,setLikedGarments]=useState<Set<string>>(new Set()),[likedOutfits,setLikedOutfits]=useState<Set<string>>(new Set()),[saved,setSaved]=useState<Set<string>>(new Set()),[notified,setNotified]=useState<Set<string>>(new Set());
 const scope=mode==="garments"?gScope:oScope;
 const brands=[...new Set(garments.map(g=>g.brand))]; const models=[...new Set(garments.filter(g=>brand==="All"||g.brand===brand).map(g=>g.name))]; const types=[...new Set(garments.filter(g=>category==="All"||g.category===category).map(g=>g.type))]; const stylesList=[...new Set(garments.filter(g=>type==="All"||g.type===type).map(g=>g.style))]; const colors=[...new Set(garments.map(g=>g.color))];
 const filteredG=useMemo(()=>garments.filter(g=>(category==="All"||g.category===category)&&(type==="All"||g.type===type)&&(style==="All"||g.style===style)&&(brand==="All"||g.brand===brand)&&(model==="All"||g.name===model)&&(color==="All"||g.color===color)),[category,type,style,brand,model,color]);
 const filteredO=useMemo(()=>outfits.filter(o=>(oType==="All"||o.type===oType)&&(season==="All"||o.season===season)),[oType,season]);
 const rankedG=useMemo(()=>{const a=filteredG.filter(g=>gScope==="all"||g.match>=75);return [...a].sort((x,y)=>gSort==="newest"?x.age-y.age:gSort==="liked"?y.likes-x.likes:gScope==="all"?hot(y.likes,y.age)-hot(x.likes,x.age):fitTiers(x.match)-fitTiers(y.match)||y.match-x.match||x.age-y.age||y.likes-x.likes)},[filteredG,gScope,gSort]);
 const rankedO=useMemo(()=>{const a=filteredO.filter(o=>oScope==="all"||o.match>=75);return [...a].sort((x,y)=>oSort==="newest"?x.age-y.age:oSort==="liked"?y.likes-x.likes:oScope==="all"?hot(y.likes,y.age)-hot(x.likes,x.age):fitTiers(x.match)-fitTiers(y.match)||y.match-x.match||x.age-y.age||y.likes-x.likes)},[filteredO,oScope,oSort]);
 const carousel=(mode==="garments"?rankedG:rankedO).slice(0,8); const results=(mode==="garments"?rankedG:rankedO).slice(8,8+limit);
 const q=query.trim().toLowerCase(); const searchG=q?garments.filter(g=>`${g.brand} ${g.name} ${g.category} ${g.type} ${g.style} ${g.color} ${g.wearer}`.toLowerCase().includes(q)):[]; const searchO=q?outfits.filter(o=>`${o.creator} ${o.caption} ${o.type} ${o.season}`.toLowerCase().includes(q)):[]; const searchP=q?people.filter(p=>`${p.name} ${p.username}`.toLowerCase().includes(q)):[];
 function open(next:Overlay){if(!next)return;if(overlay)setStack(s=>[...s,overlay]);setOverlay(next)} function back(){setStack(s=>{const n=[...s];setOverlay(n.pop()??null);return n})} function close(){setOverlay(null);setStack([])}
 function toggle(setter:typeof setSaved,id:string){setter(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n})}
 return <>
  <div className={styles.notice}>Vercel Preview Demo · test data only · production database untouched</div>
  <form className={styles.search} onSubmit={e=>{e.preventDefault();setSearchOpen(Boolean(q));setSearchTab("all")}}><span>⌕</span><input value={query} onChange={e=>{setQuery(e.target.value);if(!e.target.value.trim())setSearchOpen(false)}} placeholder="Search garments, outfits, or people"/><button className="primaryButton">Search</button></form>
  {searchOpen?<SearchResults tab={searchTab} setTab={setSearchTab} gs={searchG} os={searchO} ps={searchP} open={open}/>:<>
   <div className={styles.mainTabs}><button className={mode==="garments"?styles.active:""} onClick={()=>{setMode("garments");setLimit(24)}}>Garments</button><button className={mode==="outfits"?styles.active:""} onClick={()=>{setMode("outfits");setLimit(24)}}>Outfits</button></div>
   <div className={styles.toolbar}><div className={styles.scope}><button className={scope==="matches"?styles.active:""} onClick={()=>mode==="garments"?setGScope("matches"):setOScope("matches")}>My Fit Matches</button><button className={scope==="all"?styles.active:""} onClick={()=>mode==="garments"?setGScope("all"):setOScope("all")}>All</button></div><label>Sort <select value={mode==="garments"?gSort:oSort} onChange={e=>mode==="garments"?setGSort(e.target.value):setOSort(e.target.value)}>{scope==="matches"?<option value="best">Best Match</option>:<option value="popular">Popular</option>}<option value="newest">Newest</option><option value="liked">Most Liked</option></select></label></div>
   {mode==="garments"?<><div className={styles.categoryRow}>{categories.map(c=><button className={category===c?styles.filterActive:""} key={c} onClick={()=>{setCategory(c);setType("All");setStyle("All")}}>{c}</button>)}</div><div className={styles.filters}><label>Type<select value={type} onChange={e=>{setType(e.target.value);setStyle("All")}}><option>All</option>{types.map(v=><option key={v}>{v}</option>)}</select></label><label>Style<select value={style} onChange={e=>setStyle(e.target.value)}><option>All</option>{stylesList.map(v=><option key={v}>{v}</option>)}</select></label><label>Brand<select value={brand} onChange={e=>{setBrand(e.target.value);setModel("All")}}><option>All</option>{brands.map(v=><option key={v}>{v}</option>)}</select></label><label>Model<select value={model} onChange={e=>setModel(e.target.value)} disabled={brand==="All"}><option>All</option>{models.map(v=><option key={v}>{v}</option>)}</select></label><label>Color<select value={color} onChange={e=>setColor(e.target.value)}><option>All</option>{colors.map(v=><option key={v}>{v}</option>)}</select></label></div></>:<div className={styles.filters}><label>Type<select value={oType} onChange={e=>setOType(e.target.value)}>{outfitTypes.map(v=><option key={v}>{v}</option>)}</select></label><label>Season<select value={season} onChange={e=>setSeason(e.target.value)}>{seasons.map(v=><option key={v}>{v}</option>)}</select></label></div>}
   {(mode==="garments"?rankedG:rankedO).length===0?<div className="emptyState"><span className="eyebrow">NO RESULTS</span><h2>{scope==="matches"?"No Fit Matches yet.":"No results with these filters."}</h2><button className="secondaryButton" onClick={()=>mode==="garments"?setGScope("all"):setOScope("all")}>Browse All</button></div>:<><section><div className="sectionHeading"><div><span className="eyebrow">FOR YOU</span><h2>{mode==="garments"?(scope==="matches"?"Popular Near Your Fit":"Popular Garments"):(scope==="matches"?"Styled by People Like You":"Popular Outfits")}</h2></div></div><div className={styles.carousel}>{carousel.map(item=>mode==="garments"?<GarmentCard key={(item as Garment).id} g={item as Garment} scope={gScope} onOpen={()=>open({kind:"garment",id:(item as Garment).id})}/>:<OutfitCard key={(item as Outfit).id} o={item as Outfit} onOpen={()=>open({kind:"outfit",id:(item as Outfit).id})}/>)}</div></section><section><div className="sectionHeading"><div><span className="eyebrow">{scope==="matches"?"MY FIT MATCHES":"ALL"}</span><h2>{mode==="garments"?(scope==="matches"?"Garments matched to you":"Every Shared garment"):(scope==="matches"?"Outfits from people like you":"Every Shared outfit")}</h2></div></div><div className={styles.grid}>{results.map(item=>mode==="garments"?<GarmentCard key={(item as Garment).id} g={item as Garment} scope={gScope} onOpen={()=>open({kind:"garment",id:(item as Garment).id})}/>:<OutfitCard key={(item as Outfit).id} o={item as Outfit} onOpen={()=>open({kind:"outfit",id:(item as Outfit).id})}/>)}</div>{8+limit<(mode==="garments"?rankedG:rankedO).length?<button className="secondaryButton" onClick={()=>setLimit(v=>v+24)}>Keep Browsing</button>:<div className={styles.end}>{scope==="matches"?<><strong>You’ve reached the end of your Fit Matches.</strong><button className="textLink" onClick={()=>mode==="garments"?setGScope("all"):setOScope("all")}>Browse All {mode==="garments"?"Garments":"Outfits"} →</button></>:"You’ve reached the end."}</div>}</section></>}
  </>}
  {overlay?<OverlayView state={overlay} stack={stack} back={back} close={close} open={open} likedGarments={likedGarments} likedOutfits={likedOutfits} saved={saved} notified={notified} toggle={toggle} setLikedGarments={setLikedGarments} setLikedOutfits={setLikedOutfits} setSaved={setSaved} setNotified={setNotified}/>:null}
 </>
}

function GarmentCard({g,scope,onOpen}:{g:Garment;scope:Scope;onOpen:()=>void}){return <article className={styles.card}><button className={styles.cardOpen} onClick={onOpen}><div className={styles.fakeImage}><span>{g.type}</span><b>♡ {g.likes}</b></div><div className={styles.cardBody}><small>{g.brand}</small><h3>{g.name}</h3><p>{g.type} · {g.color}</p>{scope==="matches"?<strong>{g.type} Match {g.match}%</strong>:<strong>Closest Fit Match {g.match}%</strong>}</div></button><div className={styles.meta}>Worn by <b>{g.wearer}</b><span>{g.fit} · Size {g.size}</span></div></article>}
function OutfitCard({o,onOpen}:{o:Outfit;onOpen:()=>void}){return <article className={styles.card}><button className={styles.cardOpen} onClick={onOpen}><div className={`${styles.fakeImage} ${styles.outfitImage}`}><span>OUTFIT</span><b>♥ {o.likes}</b></div><div className={styles.cardBody}><small>Styled by {o.creator}</small><h3>{o.caption}</h3><p>{o.type} · {o.season}</p><strong>Overall Match {o.match}%</strong></div></button></article>}
function SearchResults({tab,setTab,gs,os,ps,open}:{tab:SearchTab;setTab:(t:SearchTab)=>void;gs:Garment[];os:Outfit[];ps:Person[];open:(o:Overlay)=>void}){const total=gs.length+os.length+ps.length;return <section><div className="sectionHeading"><div><span className="eyebrow">SEARCH RESULTS</span><h2>{total} matches across LikeSized</h2></div></div><div className={styles.mainTabs}>{(["all","garments","outfits","people"] as SearchTab[]).map(t=><button key={t} className={tab===t?styles.active:""} onClick={()=>setTab(t)}>{t[0].toUpperCase()+t.slice(1)}</button>)}</div>{total===0?<div className="emptyState"><h2>No results.</h2><p>Search checks all garments, outfits, and people—not only your Fit Matches.</p></div>:<>{(tab==="all"||tab==="garments")&&gs.length?<ResultGroup title="Garments">{gs.slice(0,tab==="all"?4:24).map(g=><GarmentCard key={g.id} g={g} scope="all" onOpen={()=>open({kind:"garment",id:g.id})}/>)}</ResultGroup>:null}{(tab==="all"||tab==="outfits")&&os.length?<ResultGroup title="Outfits">{os.slice(0,tab==="all"?4:24).map(o=><OutfitCard key={o.id} o={o} onOpen={()=>open({kind:"outfit",id:o.id})}/>)}</ResultGroup>:null}{(tab==="all"||tab==="people")&&ps.length?<ResultGroup title="People">{ps.map(p=><button className={styles.personCard} key={p.id} onClick={()=>open({kind:"person",id:p.id})}><span>{p.name}</span><b>{p.overall}% Overall Match</b><small>{p.fitTwins.toLocaleString()} Fit Twins · {p.styleLikes.toLocaleString()} Style Likes</small></button>)}</ResultGroup>:null}</>}</section>}
function ResultGroup({title,children}:{title:string;children:React.ReactNode}){return <section><div className="sectionHeading"><div><span className="eyebrow">{title.toUpperCase()}</span><h2>{title}</h2></div></div><div className={styles.grid}>{children}</div></section>}

function OverlayView({state,stack,back,close,open,likedGarments,likedOutfits,saved,notified,toggle,setLikedGarments,setLikedOutfits,setSaved,setNotified}:{state:NonNullable<Overlay>;stack:Overlay[];back:()=>void;close:()=>void;open:(o:Overlay)=>void;likedGarments:Set<string>;likedOutfits:Set<string>;saved:Set<string>;notified:Set<string>;toggle:(setter:React.Dispatch<React.SetStateAction<Set<string>>>,id:string)=>void;setLikedGarments:React.Dispatch<React.SetStateAction<Set<string>>>;setLikedOutfits:React.Dispatch<React.SetStateAction<Set<string>>>;setSaved:React.Dispatch<React.SetStateAction<Set<string>>>;setNotified:React.Dispatch<React.SetStateAction<Set<string>>>}){return <div className={styles.backdrop} onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><div className={styles.overlay}><header><button onClick={back} disabled={!stack.length}>← Back</button><button onClick={close}>✕</button></header>{state.kind==="garment"?<GarmentDetail g={garments.find(g=>g.id===state.id)!} open={open} liked={likedGarments.has(state.id)} saved={saved.has(state.id)} notify={notified.has(state.id)} onLike={()=>toggle(setLikedGarments,state.id)} onSave={()=>toggle(setSaved,state.id)} onNotify={()=>{setSaved(s=>new Set(s).add(state.id));toggle(setNotified,state.id)}}/>:state.kind==="outfit"?<OutfitDetail o={outfits.find(o=>o.id===state.id)!} open={open} liked={likedOutfits.has(state.id)} saved={saved.has(state.id)} onLike={()=>toggle(setLikedOutfits,state.id)} onSave={()=>toggle(setSaved,state.id)}/>:<PersonDetail p={people.find(p=>p.id===state.id)!} open={open}/>}</div></div>}
function GarmentDetail({g,open,liked,saved,notify,onLike,onSave,onNotify}:{g:Garment;open:(o:Overlay)=>void;liked:boolean;saved:boolean;notify:boolean;onLike:()=>void;onSave:()=>void;onNotify:()=>void}){const same=garments.filter(x=>x.brand===g.brand&&x.name===g.name).sort((a,b)=>b.match-a.match);return <div className={styles.detail}><div className={styles.detailHero}><div className={styles.bigImage}>{g.type}</div><div><span className="eyebrow">{g.brand}</span><h2>{g.name}</h2><p>{g.type} · {g.style} · {g.color}</p><div className={styles.bigMatch}>{g.match}% <span>Closest Fit Match</span></div><div className={styles.stats}><span>Latest Shared Fit <b>{g.wearer}</b></span><span>Size <b>{g.size}</b></span><span>Fit Result <b>{g.fit}</b></span><span>Overall Match <b>{g.overall}%</b></span></div><div className={styles.actions}><button onClick={onLike}>{liked?"♥ Liked":"♡ Like"}</button><button onClick={onSave}>{saved?"Saved":"Save"}</button><button onClick={onNotify}>{notify?"Notifications On":"Notify"}</button></div></div></div><button className={styles.wearer} onClick={()=>open({kind:"person",id:g.wearerId})}>Worn by <b>{g.wearer}</b> →</button>{same.length>1?<div><h3>View More Fit Reports ({same.length})</h3><div className={styles.reportList}>{same.map(r=><button key={r.id} onClick={()=>open({kind:"garment",id:r.id})}><b>{r.wearer}</b><span>{r.match}% Match</span><span>Size {r.size}</span><span>{r.fit}</span></button>)}</div></div>:null}<button className="secondaryButton">View Full Product Details →</button></div>}
function OutfitDetail({o,open,liked,saved,onLike,onSave}:{o:Outfit;open:(s:Overlay)=>void;liked:boolean;saved:boolean;onLike:()=>void;onSave:()=>void}){return <div className={styles.detail}><div className={`${styles.bigImage} ${styles.outfitBig}`}>OUTFIT PHOTO</div><button className={styles.wearer} onClick={()=>open({kind:"person",id:o.creatorId})}>Styled by <b>{o.creator}</b> · {o.match}% Overall Match →</button><p className={styles.caption}>{o.caption}</p><div className={styles.actions}><button onClick={onLike}>{liked?"♥ Liked":"♡ Like"} · {o.likes}</button><button onClick={onSave}>{saved?"Saved to LikeLocker":"Save to LikeLocker"}</button></div><h3>Tagged garments</h3><div className={styles.tagged}>{o.garments.map(id=>{const g=garments.find(x=>x.id===id)!;return <button key={id} onClick={()=>open({kind:"garment",id})}><b>{g.brand} · {g.name}</b><span>Size {g.size}</span><span>{g.match}% Match</span></button>})}</div><button className="secondaryButton" onClick={()=>open({kind:"person",id:o.creatorId})}>See More Styles from {o.creator}</button></div>}
function PersonDetail({p,open}:{p:Person;open:(s:Overlay)=>void}){const recentO=outfits.filter(o=>o.creatorId===p.id).slice(0,3);const recentG=garments.filter(g=>g.wearerId===p.id).slice(0,3);return <div className={styles.detail}><div className={styles.personHero}><div className={styles.avatar}>{p.name.split(" ").map(v=>v[0]).join("")}</div><div><h2>{p.name}</h2><span>@{p.username}</span><div className={styles.matchRow}><b>{p.overall}% Overall</b><b>{p.tops}% Tops</b><b>{p.bottoms}% Bottoms</b></div><p>{p.fitTwins.toLocaleString()} Fit Twins · {p.styleLikes.toLocaleString()} Style Likes</p><div className={styles.actions}><button>Fit Twin</button><button>Notify</button></div></div></div><h3>Recent Shared posts</h3><div className={styles.tagged}>{recentG.slice(0,2).map(g=><button key={g.id} onClick={()=>open({kind:"garment",id:g.id})}><b>{g.brand} · {g.name}</b><span>{g.match}% garment match</span></button>)}{recentO.slice(0,1).map(o=><button key={o.id} onClick={()=>open({kind:"outfit",id:o.id})}><b>Outfit</b><span>{o.caption}</span></button>)}</div><button className="primaryButton">View Their Closet →</button></div>}
