import Link from "next/link";
import { redirect } from "next/navigation";
import { addToWishLocker, likeProduct, removeFromWishLocker, unlikeProduct } from "@/app/likelocker/actions";
import { outfitFeedPhotoPath } from "@/lib/outfit-photo-paths";
import { createClient } from "@/lib/supabase/server";
import styles from "./explore.module.css";

type SearchParams=Promise<Record<string,string|string[]|undefined>>;
type Product={id:string;name:string;slug:string;category:string;garment_type_key:string|null;image_url:string|null;brand:unknown};
type Brand={name:string};
type Outfit={id:string;user_id:string;caption:string|null;photo_url:string;created_at:string;profile:unknown};
type Profile={username:string;display_name:string|null};
type Match={user_id:string;username:string;display_name:string|null;avatar_url:string|null;match_score:number};
type Evidence={historical_match_score:number};
type Person={id:string;username:string;display_name:string|null;avatar_url:string|null};
const LABELS:Record<string,string>={tops:"Tops",bottoms:"Bottoms",dresses:"Dresses",outerwear:"Outerwear",shoes:"Shoes",other:"Other"};
function first(v:string|string[]|undefined){return Array.isArray(v)?v[0]:v;}
function one<T>(v:unknown):T|null{return Array.isArray(v)?((v[0] as T|undefined)??null):((v as T|null)??null);}
function clean(v:string|undefined){return (v??"").trim().replace(/%/g,"").replace(/\s+/g," ").slice(0,80);}
function tier(score:number){if(score>=90)return "Exceptional fit evidence";if(score>=85)return "Strong fit evidence";if(score>=80)return "Good fit evidence";return "Useful fit evidence";}

export default async function ExplorePage({searchParams}:{searchParams:SearchParams}){
 const params=await searchParams;const view=first(params.view)==="outfits"?"outfits":"garments";const scope=first(params.scope)==="all"?"all":"matches";const q=clean(first(params.q));const category=clean(first(params.category));const supabase=await createClient();
 const {data:claims,error:claimsError}=await supabase.auth.getClaims();const viewerId=claims?.claims?.sub;if(claimsError||!viewerId)redirect("/login?next=/browse");
 const [{data:profile},{data:fitProfile},{data:matchData,error:matchError}]=await Promise.all([supabase.from("profiles").select("username").eq("id",viewerId).maybeSingle(),supabase.from("fit_profiles").select("completed_at").eq("user_id",viewerId).maybeSingle(),supabase.rpc("get_fit_matches",{p_match_category:"overall",p_result_limit:100})]);
 if(!profile?.username||!fitProfile?.completed_at)redirect("/onboarding");if(matchError)throw new Error("Could not load Explore matches.");
 const matches=(matchData??[]) as Match[];const matchByUser=new Map(matches.map(row=>[row.user_id,row.match_score]));
 let products:Product[]=[];let people:Person[]=[];
 if(view==="garments"){
  if(q){const {data,error}=await supabase.rpc("search_catalog_products",{p_query:q,p_result_limit:24});if(error)throw new Error("Could not search garments.");const ids=(data??[]).map((row:{id:string})=>row.id);if(ids.length){const result=await supabase.from("products").select("id,name,slug,category,garment_type_key,image_url,brand:brands(name)").in("id",ids);if(result.error)throw new Error("Could not load garments.");products=(result.data??[]) as Product[];}}
  else{let query=supabase.from("products").select("id,name,slug,category,garment_type_key,image_url,brand:brands(name)").neq("catalog_status","rejected").order("created_at",{ascending:false}).limit(24);if(category)query=query.eq("category",category);const result=await query;if(result.error)throw new Error("Could not load garments.");products=(result.data??[]) as Product[];}
  if(q){const {data}=await supabase.rpc("search_members",{p_query:q,p_result_limit:8});people=(data??[]) as Person[];}
 }
 const scores=new Map<string,number>();
 if(view==="garments"&&products.length){await Promise.all(products.map(async product=>{const {data}=await supabase.rpc("get_product_evidence_candidates",{p_product_id:product.id,p_variant_id:null,p_result_limit:40});const best=Math.max(...((data??[]) as Evidence[]).map(row=>row.historical_match_score),0);scores.set(product.id,best);}));if(scope==="matches")products=products.filter(product=>(scores.get(product.id)??0)>=75);products.sort((a,b)=>(scores.get(b.id)??0)-(scores.get(a.id)??0));}
 let outfits:Outfit[]=[];
 if(view==="outfits"){let query=supabase.from("outfit_posts").select("id,user_id,caption,photo_url,created_at,profile:profiles(username,display_name)").order("created_at",{ascending:false}).limit(24);const result=await query;if(result.error)throw new Error("Could not load outfits.");outfits=(result.data??[]) as Outfit[];if(scope==="matches")outfits=outfits.filter(post=>(matchByUser.get(post.user_id)??0)>=75);if(q)outfits=outfits.filter(post=>{const p=one<Profile>(post.profile);return `${post.caption??""} ${p?.username??""} ${p?.display_name??""}`.toLowerCase().includes(q.toLowerCase());});outfits.sort((a,b)=>(matchByUser.get(b.user_id)??0)-(matchByUser.get(a.user_id)??0));}
 const [{data:likedData},{data:wishedData}]=await Promise.all([supabase.from("product_likes").select("product_id").eq("user_id",viewerId),supabase.from("wish_locker_items").select("product_id").eq("user_id",viewerId)]);const liked=new Set((likedData??[]).map(row=>row.product_id));const wished=new Set((wishedData??[]).map(row=>row.product_id));
 const signed=new Map<string,string>();await Promise.all(outfits.map(async post=>{const feedPath=outfitFeedPhotoPath(post.photo_url);let {data}=await supabase.storage.from("outfit-photos").createSignedUrl(feedPath,1800);if(!data?.signedUrl&&feedPath!==post.photo_url)({data}=await supabase.storage.from("outfit-photos").createSignedUrl(post.photo_url,1800));if(data?.signedUrl)signed.set(post.id,data.signedUrl);}));
 const base=`/browse?view=${view}&scope=${scope}${category?`&category=${encodeURIComponent(category)}`:""}${q?`&q=${encodeURIComponent(q)}`:""}`;
 return <main className="pageShell"><div className="pageTitle"><span className="eyebrow">EXPLORE</span><h1>Discover clothes through real fit evidence.</h1><p>Start with garments and outfits backed by members whose fit data is most relevant to you. Switch to All whenever you want the wider catalog.</p></div>
 <form className={styles.search} action="/browse"><input type="hidden" name="view" value={view}/><input type="hidden" name="scope" value={scope}/><input name="q" type="search" defaultValue={q} placeholder="Search products, brands, outfits, or people" maxLength={80}/><button className="primaryButton">Search</button></form>
 <div className={styles.controls}><nav className="filterBar" aria-label="Explore content"><Link className={`filter${view==="garments"?" active":""}`} href="/browse?view=garments&scope=matches">Garments</Link><Link className={`filter${view==="outfits"?" active":""}`} href="/browse?view=outfits&scope=matches">Outfits</Link></nav><nav className="filterBar" aria-label="Explore scope"><Link className={`filter${scope==="matches"?" active":""}`} href={`/browse?view=${view}&scope=matches`}>My Fit Matches</Link><Link className={`filter${scope==="all"?" active":""}`} href={`/browse?view=${view}&scope=all`}>All</Link></nav></div>
 {view==="garments"&&!q?<nav className={styles.categories} aria-label="Garment categories"><Link className={!category?styles.activeCategory:styles.category} href={`/browse?view=garments&scope=${scope}`}>All garments</Link>{Object.entries(LABELS).map(([key,label])=><Link key={key} className={category===key?styles.activeCategory:styles.category} href={`/browse?view=garments&scope=${scope}&category=${key}`}>{label}</Link>)}</nav>:null}
 {scope==="matches"?<p className={styles.explainer}>My Fit Matches shows 75%+ evidence first. Match % is relevance—not a guarantee that a garment will fit.</p>:null}
 {view==="garments"&&products.length?<div className={styles.grid}>{products.map(product=>{const brand=one<Brand>(product.brand);const score=scores.get(product.id)??0;return <article className={styles.card} key={product.id}><Link className={styles.imageLink} href={`/item/${product.slug}`}>{product.image_url?<img src={product.image_url} alt={`${brand?.name??""} ${product.name}`.trim()}/>:<div className={styles.fallback}>{product.name.replace(/[^A-Za-z0-9]/g,"").slice(0,2).toUpperCase()||"LS"}</div>}</Link><div className={styles.body}><span className="muted">{brand?.name||"Brand"} · {LABELS[product.category]||"Garment"}</span><Link className={styles.title} href={`/item/${product.slug}`}>{product.name}</Link>{score?<div><strong>{score}% historical Match</strong><span className="muted">{tier(score)}</span></div>:<span className="muted">Fit evidence is still growing.</span>}<div className={styles.actions}><form action={liked.has(product.id)?unlikeProduct:likeProduct}><input type="hidden" name="product_id" value={product.id}/><input type="hidden" name="return_to" value={base}/><button type="submit" aria-pressed={liked.has(product.id)}>{liked.has(product.id)?"♥ Liked":"♡ Like"}</button></form><form action={wished.has(product.id)?removeFromWishLocker:addToWishLocker}><input type="hidden" name="product_id" value={product.id}/><input type="hidden" name="return_to" value={base}/><button type="submit" aria-pressed={wished.has(product.id)}>{wished.has(product.id)?"In Wish Locker":"+ Wish Locker"}</button></form></div></div></article>;})}</div>:null}
 {view==="outfits"&&outfits.length?<div className={styles.grid}>{outfits.map(post=>{const p=one<Profile>(post.profile);const name=p?.display_name?.trim()||p?.username||"LikeSized member";const score=matchByUser.get(post.user_id);return <article className={styles.card} key={post.id}>{signed.get(post.id)?<img className={styles.outfit} src={signed.get(post.id)} alt={`Outfit by ${name}`}/>:<div className={styles.outfitFallback}>Outfit photo unavailable</div>}<div className={styles.body}><span className="muted">{score?`${score}% Overall Match`:"LikeSized member"}</span><strong>{name}</strong>{post.caption?<p>{post.caption}</p>:null}{p?.username?<Link className="textLink" href={`/people/${p.username}`}>View wearer →</Link>:null}</div></article>;})}</div>:null}
 {q&&people.length?<section><div className="sectionHeading"><div><span className="eyebrow">PEOPLE</span><h2>People matching “{q}”</h2></div></div><div className={styles.people}>{people.map(person=><Link href={`/people/${person.username}`} key={person.id}><strong>{person.display_name?.trim()||person.username}</strong><span>@{person.username}{typeof matchByUser.get(person.id)==="number"?` · ${matchByUser.get(person.id)}% Overall Match`:""}</span></Link>)}</div></section>:null}
 {((view==="garments"&&!products.length)||(view==="outfits"&&!outfits.length))?<div className="emptyState"><span className="eyebrow">MORE EVIDENCE NEEDED</span><h2>{scope==="matches"?"No 75%+ matches are available in this view yet.":"Nothing matches these filters yet."}</h2><p>Try All, clear the search, or choose another category. Explore will grow automatically as members add real fit reports and outfits.</p><Link className="secondaryButton" href={`/browse?view=${view}&scope=all`}>See all {view} →</Link></div>:null}</main>;
}
