"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { reportProductItem } from "@/app/item/[slug]/actions";
import { addToWishLocker, likeProduct, removeFromWishLocker, unlikeProduct } from "@/app/likelocker/actions";
import { SwipeDismissImageLightbox } from "@/components/SwipeDismissImageLightbox";
import { UniversalActionBar, UniversalActionButton, UniversalActionLink, UniversalActionSummary } from "@/components/UniversalActionBar";
import quickStyles from "./TaggedItemsPanel.module.css";
import styles from "./outfitDetail.module.css";

export type TaggedItem={closetItemId:string;productId:string;label:string;detail:string;href:string;imageUrl:string|null;liked:boolean;wished:boolean;canShop:boolean};
type RelevantReport={fitReportId:string;bodyMatch:number;sizeLabel:string;fitLabel:string;isOwn:boolean};
type Recommendation={sizeLabel:string;confidence:number;confidenceLabel:string;similarWearerCount:number;sizeEvidenceCount:number};
type FitMeta={category:string;profileReady:boolean;matchingFitReports:number;objectiveVariantKey:string;recommendation:Recommendation|null;relevantReports:RelevantReport[]};

export default function TaggedItemsPanel({items,postId,signedIn}:{items:TaggedItem[];postId:string;signedIn:boolean}){
  const [selectedId,setSelectedId]=useState<string|null>(null);const [gateItem,setGateItem]=useState<TaggedItem|null>(null);const [imageOpen,setImageOpen]=useState(false);const [evidenceOpen,setEvidenceOpen]=useState(false);
  const [fitMeta,setFitMeta]=useState<Record<string,FitMeta>>({});const [fitLoading,setFitLoading]=useState<Record<string,boolean>>({});
  const [liked,setLiked]=useState<Record<string,boolean>>(()=>Object.fromEntries(items.map((item)=>[item.productId,item.liked])));const [wished,setWished]=useState<Record<string,boolean>>(()=>Object.fromEntries(items.map((item)=>[item.productId,item.wished])));const [likePending,setLikePending]=useState<Record<string,boolean>>({});const [wishPending,setWishPending]=useState<Record<string,boolean>>({});const [actionError,setActionError]=useState("");const [watching,setWatching]=useState<Record<string,boolean>>({});const [watchPending,setWatchPending]=useState<Record<string,boolean>>({});
  const selected=items.find((item)=>item.closetItemId===selectedId)??null;const returnTo=`/outfits/${postId}?tab=tagged`;

  useEffect(()=>{
    if(!selected||!signedIn||fitMeta[selected.closetItemId]||fitLoading[selected.closetItemId])return;
    let active=true;setFitLoading((current)=>({...current,[selected.closetItemId]:true}));
    void fetch(`/api/outfits/${postId}/tagged-fit?closet_item_id=${encodeURIComponent(selected.closetItemId)}`,{cache:"no-store"}).then(async(response)=>{if(!response.ok)throw new Error();const payload=await response.json() as FitMeta;if(active)setFitMeta((current)=>({...current,[selected.closetItemId]:payload}));}).catch(()=>{if(active)setActionError("FITuition evidence could not load. Try again.");}).finally(()=>{if(active)setFitLoading((current)=>({...current,[selected.closetItemId]:false}));});
    return()=>{active=false;};
  },[selected?.closetItemId,signedIn,postId,fitMeta,fitLoading]);

  useEffect(()=>{function openFromPhoto(event:Event){const closetItemId=(event as CustomEvent<{closetItemId?:string}>).detail?.closetItemId;if(!closetItemId)return;const item=items.find((entry)=>entry.closetItemId===closetItemId);if(!item)return;if(signedIn){setEvidenceOpen(false);setSelectedId(item.closetItemId);}else setGateItem(item);}window.addEventListener("likesized:open-tagged-item",openFromPhoto);return()=>window.removeEventListener("likesized:open-tagged-item",openFromPhoto);},[items,signedIn]);

  function openItem(item:TaggedItem){if(!signedIn){setGateItem(item);return;}setEvidenceOpen(false);setActionError("");setSelectedId(item.closetItemId);}
  async function runLike(item:TaggedItem){if(likePending[item.productId])return;const next=!liked[item.productId];setActionError("");setLiked((current)=>({...current,[item.productId]:next}));setLikePending((current)=>({...current,[item.productId]:true}));const formData=new FormData();formData.set("product_id",item.productId);formData.set("return_to",returnTo);formData.set("stay_open","1");try{await(next?likeProduct:unlikeProduct)(formData);}catch{setLiked((current)=>({...current,[item.productId]:!next}));setActionError("LikeLocker could not update. Try again.");}finally{setLikePending((current)=>({...current,[item.productId]:false}));}}
  async function runWish(item:TaggedItem){if(wishPending[item.productId])return;const next=!wished[item.productId];setActionError("");setWished((current)=>({...current,[item.productId]:next}));setWishPending((current)=>({...current,[item.productId]:true}));const formData=new FormData();formData.set("product_id",item.productId);formData.set("return_to",returnTo);formData.set("stay_open","1");try{await(next?addToWishLocker:removeFromWishLocker)(formData);}catch{setWished((current)=>({...current,[item.productId]:!next}));setActionError("Wishlist could not update. Try again.");}finally{setWishPending((current)=>({...current,[item.productId]:false}));}}
  async function share(item:TaggedItem){const url=new URL(item.href,window.location.origin).toString();try{if(navigator.share)await navigator.share({title:item.label,url});else await navigator.clipboard.writeText(url);}catch{/* cancelled */}}
  async function requestWatch(item:TaggedItem){if(watchPending[item.closetItemId]||watching[item.closetItemId])return;setActionError("");setWatchPending((current)=>({...current,[item.closetItemId]:true}));try{const response=await fetch(`/api/outfits/${postId}/tagged-fit/watch`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({closetItemId:item.closetItemId})});if(!response.ok)throw new Error();setWatching((current)=>({...current,[item.closetItemId]:true}));}catch{setActionError("Notification request could not be saved. Try again.");}finally{setWatchPending((current)=>({...current,[item.closetItemId]:false}));}}

  if(!items.length)return <p className="muted">No tagged items on this Outfit.</p>;
  const meta=selected?fitMeta[selected.closetItemId]:null;const isLoading=selected?Boolean(fitLoading[selected.closetItemId]):false;
  return <div className={styles.taggedPanel}>
    <div className={styles.taggedGrid}>{items.map((item)=><button className={styles.taggedCard} type="button" key={item.closetItemId} onClick={()=>openItem(item)}>{item.imageUrl?<img src={item.imageUrl} alt=""/>:<span className={styles.taggedFallback}>{item.label.slice(0,1).toUpperCase()}</span>}<span><strong>{item.label}</strong><small>{item.detail}</small></span></button>)}</div>

    {selected?<div className={styles.itemPreviewOverlay} role="dialog" aria-modal="true" aria-label={`${selected.label} quick view`} onClick={()=>setSelectedId(null)}><div className={styles.itemPreviewCard} onClick={(event)=>event.stopPropagation()}>
      <button className={styles.itemPreviewClose} type="button" aria-label="Close item preview" onClick={()=>setSelectedId(null)}>×</button>
      {evidenceOpen&&meta?<>
        <button className={styles.previewBack} type="button" onClick={()=>setEvidenceOpen(false)}>← Back to FITuition</button>
        <div className={styles.evidenceHeading}><span className={styles.fituitionKicker}>RELEVANT FIT REPORTS</span><strong>{selected.label}</strong><span>Exact variation · people close to your measurements</span></div>
        <div className={styles.relevantReportList}>{meta.relevantReports.map((report)=><div className={styles.relevantReport} key={report.fitReportId}><div><strong>{report.bodyMatch}%</strong><span>Body Match{report.isOwn?" · You":""}</span></div><div><span>Size</span><strong>{report.sizeLabel}</strong></div><div><span>Fit Result</span><strong>{report.fitLabel}</strong></div></div>)}</div>
      </>:<>
        <div className={styles.itemPreviewTop}>{selected.imageUrl?<button className={quickStyles.garmentImageTrigger} type="button" aria-label="Open full-size garment photo" onClick={()=>setImageOpen(true)}><img className={styles.itemPreviewImage} src={selected.imageUrl} alt=""/></button>:<div className={styles.itemPreviewFallback}>{selected.label.slice(0,1).toUpperCase()}</div>}<div className={styles.itemPreviewInfo}><strong>{selected.label}</strong><span>{meta?.category||selected.detail}</span><span>{isLoading?"Checking Fit Reports…":meta?.profileReady?`Matching Fit Reports: ${meta.matchingFitReports}`:"Complete your Fit Profile for personalized evidence."}</span></div></div>
        <section className={styles.fituitionCard} aria-label="FITuition">
          <span className={styles.fituitionKicker}>FITuition</span>
          {isLoading||!meta?<><strong className={styles.fituitionHeadline}>Checking your fit evidence…</strong><p>Comparing this exact variation with your Fit Profile and Closet history.</p></>:!meta.profileReady?<><strong className={styles.fituitionHeadline}>Build your Fit Profile to use FITuition.</strong><p>Your measurements stay private.</p></>:meta.recommendation?<><span className={styles.recommendationLabel}>Recommended size</span><div className={styles.recommendationRow}><strong className={styles.recommendedSize}>{meta.recommendation.sizeLabel}</strong><span className={styles.confidenceBadge}>{meta.recommendation.confidenceLabel}</span></div><p>I found {meta.matchingFitReports} Fit Report{meta.matchingFitReports===1?"":"s"} for this exact variation from people close to your measurements. FITuition also considered your Closet history before choosing a size.</p><button className={styles.evidenceLink} type="button" onClick={()=>setEvidenceOpen(true)}>See Relevant Fit Reports →</button></>:meta.matchingFitReports>0?<><strong className={styles.fituitionHeadline}>I’m not confident enough to recommend a size yet.</strong><p>I found {meta.matchingFitReports} Fit Report{meta.matchingFitReports===1?"":"s"} for this exact variation from people close to your measurements, but their results don’t point clearly to one size.</p><button className={styles.evidenceLink} type="button" onClick={()=>setEvidenceOpen(true)}>See Relevant Fit Reports →</button></>:<><strong className={styles.fituitionHeadline}>I don’t have Fit Reports from people close enough to your measurements yet.</strong>{watching[selected.closetItemId]?<p className={styles.watchSuccess}>You’re set. FITuition will notify you when useful evidence arrives.</p>:<button className={styles.notifyLink} type="button" disabled={Boolean(watchPending[selected.closetItemId])} onClick={()=>void requestWatch(selected)}>{watchPending[selected.closetItemId]?"Saving notification…":"Notify me when Fit Reports from people close to my measurements are posted"}</button>}</>}
        </section>
        <UniversalActionBar className={styles.itemPreviewActions} ariaLabel="Garment actions"><UniversalActionButton action="likeLocker" type="button" showLabel disabled={Boolean(likePending[selected.productId])} active={Boolean(liked[selected.productId])} onClick={()=>void runLike(selected)}/><UniversalActionButton action="wishLocker" type="button" showLabel disabled={Boolean(wishPending[selected.productId])} active={Boolean(wished[selected.productId])} onClick={()=>void runWish(selected)}/>{selected.canShop?<UniversalActionLink action="shop" showLabel className={styles.previewActionLink} href={`/api/outfits/${postId}/shop?product_id=${selected.productId}`} target="_blank" rel="noopener noreferrer"/>:null}<UniversalActionButton action="share" showLabel type="button" onClick={()=>void share(selected)}/><details className={styles.itemReport}><UniversalActionSummary action="report" showLabel ariaLabel="Report this garment" title="Report"/><form action={reportProductItem}><input type="hidden" name="product_id" value={selected.productId}/><input type="hidden" name="return_to" value={returnTo}/><input type="hidden" name="stay_open" value="1"/><label>Reason<select name="reason" defaultValue="" required><option value="" disabled>Select a reason</option><option value="inappropriate_content">Inappropriate content</option><option value="image_mismatch">Image mismatch</option><option value="incorrect_information">Incorrect information</option><option value="other">Other</option></select></label><label>Details <span className="muted inlineMuted">optional</span><textarea name="details" maxLength={500} rows={2}/></label><button type="submit">Send report</button></form></details></UniversalActionBar>
      </>}
      {actionError?<small role="status" className={styles.previewError}>{actionError}</small>:null}
      <Link prefetch={false} className={styles.fullDetailsLink} href={selected.href} data-full-navigation="true">View Detailed Garment Report →</Link>
    </div></div>:null}
    {selected?.imageUrl&&imageOpen?<SwipeDismissImageLightbox src={selected.imageUrl} alt={selected.label} label="Full-size garment photo" onClose={()=>setImageOpen(false)}/>:null}
    {gateItem?<div className={styles.itemPreviewOverlay} role="dialog" aria-modal="true" aria-label="Sign in to see personalized fit" onClick={()=>setGateItem(null)}><div className={styles.taggedAuthGate} onClick={(event)=>event.stopPropagation()}><button className={styles.itemPreviewClose} type="button" aria-label="Close" onClick={()=>setGateItem(null)}>×</button><span className="eyebrow">PERSONALIZED FIT</span><strong>See how {gateItem.label} fits you.</strong><p>Create an account or sign in to see Matching Fit Reports, Body Match, and FITuition for this garment.</p><div className={styles.taggedAuthActions}><Link prefetch={false} className="primaryButton" href="/signup">Create account</Link><Link prefetch={false} className="secondaryButton" href={`/login?next=${encodeURIComponent(returnTo)}`}>Sign in</Link></div></div></div>:null}
  </div>;
}
