export const OUTFIT_OCCASIONS = [
  { value: "beach", label: "Beach" },
  { value: "brunch", label: "Brunch" },
  { value: "business_casual", label: "Business Casual" },
  { value: "business_formal", label: "Business Formal" },
  { value: "concert", label: "Concert" },
  { value: "date_night", label: "Date Night" },
  { value: "dinner", label: "Dinner" },
  { value: "everyday", label: "Everyday" },
  { value: "festival", label: "Festival" },
  { value: "formal_event", label: "Formal Event" },
  { value: "golf", label: "Golf" },
  { value: "gym_workout", label: "Gym/Workout" },
  { value: "holiday_special_occasion", label: "Holiday/Special Occasion" },
  { value: "lounge_home", label: "Lounge/Home" },
  { value: "night_out", label: "Night Out" },
  { value: "outdoors", label: "Outdoors" },
  { value: "party", label: "Party" },
  { value: "poolside", label: "Poolside" },
  { value: "running_errands", label: "Running Errands" },
  { value: "school_campus", label: "School/Campus" },
  { value: "travel", label: "Travel" },
  { value: "vacation_resort", label: "Vacation/Resort" },
  { value: "wedding_guest", label: "Wedding Guest" },
  { value: "work", label: "Work" },
] as const;

export const OUTFIT_OCCASION_LABELS = new Map(OUTFIT_OCCASIONS.map((item) => [item.value, item.label]));
