import Link from "next/link";
import { cache } from "react";
import { MatchPercentageBadge } from "@/components/MatchPercentageBadge";
import type { EvidenceLevel } from "@/lib/domain";
import { STRONG_FIT_REPORT_MATCH_THRESHOLD, FIT_RESULT_LABELS } from "@/lib/quick-fit-evidence";
import { buildSafeSizeAdjacency, closetEvidenceRelevance, recommendSize, recommendationConfidenceLabel, simpleAlphaAdjacency, type NormalizedSizeDescriptor, type RecommendationEvidence } from "@/lib/recommendation";
import { createClient } from "@/lib/supabase/server";
import GarmentNotifyButton from "./GarmentNotifyButton";
import styles from "./itemDetail.module.css";

type ProductRecord={id:string;category:string;garment_type_key:string|null;brand_id:string;product_family_id:string|null};
type Candidate={fit_report_id:string;user_id:string;closet_item_id:string;evidence_product_id:string;evidence_variant_id:string|null;fit_profile_version_id:string;original_size_label:string;normalized_size_id:string|null;fit:RecommendationEvidence["fit"];would_buy_again:boolean;historical_match_score:number;historical_coverage_percent:number;evidence_level:EvidenceLevel;evidence_rank:number;attribute_overlap:number;directional_fit_support:number|null};
type CandidateMeta={id:string;tracked_variation_key:string|null;created_at:string};
type Profile={id:string;username:string;display_name:string|null};
type EvidenceProduct={id:string;name:string;slug:string;brand_id:string;product_family_id:string|null;garment_type_key:string|null;category:string};
type SizeRow={id:string;normalized_key:string;display_label:string;kind:string;sizing_system:string|null;alpha_size:string|null;numeric_size:number|null;shoe_size:number|null};
type OwnReport={id:string;user_id:string;product_id:string;normalized_size_id:string|null;size_label:string;fit:RecommendationEvidence["fit"];created_at:string;garment_condition:string;tracked_variation_key:string|null};
type SnapshotMatch={fit_report_id:string;historical_match_score:number;historical_coverage_percent:number};
type AttributeRow={product_id:string;attribute_key:string;option_key:string};
type Adjacency={current:{sizeKey:string;sizeLabel:string};up:{sizeKey:string;sizeLabel:string}|null;down:{sizeKey:string;sizeLabel:string}|null};
type StrongGroup={size:string;count:number;fits:Array<{fit:string;label:string;count:number;percent:number}>};
type FituitionData={recommendation:ReturnType<typeof recommendSize>;mixed:boolean;exactCandidates:Candidate[];strongGroups:StrongGroup[];profileById:Map<string,Profile>;sizeFor:(row:Candidate)=>string};

function attributeSets(rows:AttributeRow[]){const result=new Map<string,Set<string>>();for(const row of rows){const set=result.get(row.product_id)??new Set<string>();set.add(`${row.attribute_key}:${row.option_key}`);result.set(row.product_id,set);}return result;}
function overlap(a:Set<string>|undefined,b:Set<string>|undefined){if(!a||!b)return 0;let count=0;for(const value of a)if(b.has(value))count+=1;return count;}
function sizeAdjacency(normalizedId:string|null,sizeLabel:string,byId:Map<string,SizeRow>,safe:Map<string,Adjacency>):Adjacency{if(normalizedId){const mapped=safe.get(normalizedId);if(mapped)return mapped;const normalized=byId.get(normalizedId);if(normalized)return{current:{sizeKey:normalized.normalized_key,sizeLabel:normalized.display_label},up:null,down:null};}const alpha=simpleAlphaAdjacency(sizeLabel);if(alpha.current)return{current:alpha.current,up:alpha.up,down:alpha.down};return{current:{sizeKey:`raw:${sizeLabel.trim().toUpperCase()}`,sizeLabel},up:null,down:null};}
function dedupeCandidates(rows:Candidate[],metaById:Map<string,CandidateMeta>){const ordered=[...rows].sort((a,b)=>(metaById.get(b.fit_report_id)?.created_at??"").localeCompare(metaById.get(a.fit_report_id)?.created_at??"")||b.fit_report_id.localeCompare(a.fit_report_id));const seen=new Set<string>();const result:Candidate[]=[];for(const row of ordered){const meta=metaById.get(row.fit_report_id);const key=`${row.user_id}:${row.evidence_product_id}:${meta?.tracked_variation_key??row.fit_report_id}`;if(seen.has(key))continue;seen.add(key);result.push(row);}return result;}
function evidenceLevel(row:Candidate,meta:CandidateMeta|undefined,productId:string,selectedVariation:string|null):EvidenceLevel{if(row.evidence_product_id===productId&&selectedVariation&&meta?.tracked_variation_key===selectedVariation)return"exact_variant";if(row.evidence_product_id===productId)return"exact_product";return row.evidence_level;}
function closetLevel(report:OwnReport,target:ProductRecord,source:EvidenceProduct,selectedVariation:string|null,attributeOverlap:number):EvidenceLevel{if(report.product_id===target.id&&selectedVariation&&report.tracked_variation_key===selectedVariation)return"exact_variant";if(report.product_id===target.id)return"exact_product";if(target.product_family_id&&source.product_family_id===target.product_family_id)return"product_family";if(source.garment_type_key===target.garment_type_key&&attributeOverlap>0)return"similar_garments";if(source.brand_id===target.brand_id&&source.garment_type_key===target.garment_type_key)return"brand_garment_type";return"category_fit";}
function aggregateStrong(rows:Candidate[],sizeFor:(row:Candidate)=>string):StrongGroup[]{const bySize=new Map<string,{count:number;fits:Map<string,number>}>();for(const row of rows){const size=sizeFor(row);const group=bySize.get(size)??{count:0,fits:new Map<string,number>()};group.count+=1;group.fits.set(row.fit,(group.fits.get(row.fit)??0)+1);bySize.set(size,group);}return[...bySize.entries()].map(([size,value])=>({size,count:value.count,fits:[...value.fits.entries()].map(([fit,count])=>({fit,label:FIT_RESULT_LABELS[fit]??fit,count,percent:Math.round(count/value.count*100)})).sort((a,b)=>b.count-a.count)})).sort((a,b)=>b.count-a.count||a.size.localeCompare(b.size));}

const loadFituitionData=cache(async(productId:string,viewerId:string,selectedVariationKey:string|null):Promise<FituitionData>=>{
  const supabase=await createClient();
  const [{data:productData,error:productError},candidateResult,ownReportResult,sizeResult]=await Promise.all([
    supabase.from("products").select("id,category,garment_type_key,brand_id,product_family_id").eq("id",productId).maybeSingle(),
    supabase.rpc("get_product_evidence_candidates",{p_product_id:productId,p_variant_id:null,p_result_limit:300}),
    supabase.from("fit_reports").select("id,user_id,product_id,normalized_size_id,size_label,fit,created_at,garment_condition,tracked_variation_key").eq("user_id",viewerId).order("created_at",{ascending:false}).limit(200),
    supabase.from("normalized_sizes").select("id,normalized_key,display_label,kind,sizing_system,alpha_size,numeric_size,shoe_size"),
  ]);
  if(productError||!productData||candidateResult.error||ownReportResult.error||sizeResult.error)throw new Error("Could not calculate personalized garment evidence.");
  const product=productData as ProductRecord;const rawCandidates=(candidateResult.data??[]) as Candidate[];const candidateIds=[...new Set(rawCandidates.map((row)=>row.fit_report_id))];const ownReports=(ownReportResult.data??[]) as OwnReport[];const ownProductIds=[...new Set(ownReports.map((row)=>row.product_id))];const evidenceProductIds=[...new Set(rawCandidates.map((row)=>row.evidence_product_id))];const allProductIds=[...new Set([product.id,...ownProductIds,...evidenceProductIds])];
  const [candidateMetaResult,profilesResult,productsResult,snapshotResult,attributeResult]=await Promise.all([
    candidateIds.length?supabase.from("fit_reports").select("id,tracked_variation_key,created_at").in("id",candidateIds):Promise.resolve({data:[],error:null}),
    rawCandidates.length?supabase.from("profiles").select("id,username,display_name").in("id",[...new Set(rawCandidates.map((row)=>row.user_id))]):Promise.resolve({data:[],error:null}),
    allProductIds.length?supabase.from("products").select("id,name,slug,brand_id,product_family_id,garment_type_key,category").in("id",allProductIds):Promise.resolve({data:[],error:null}),
    ownReports.length?supabase.rpc("get_fit_report_snapshot_matches",{p_fit_report_ids:ownReports.map((row)=>row.id)}):Promise.resolve({data:[],error:null}),
    allProductIds.length?supabase.from("product_attribute_values").select("product_id,attribute_key,option_key").in("product_id",allProductIds).neq("source_status","rejected").gte("confidence",0.75):Promise.resolve({data:[],error:null}),
  ]);
  const candidateMeta=(candidateMetaResult.error?[]:(candidateMetaResult.data??[])) as CandidateMeta[];const metaById=new Map(candidateMeta.map((row)=>[row.id,row]));const deduped=dedupeCandidates(rawCandidates,metaById);
  const community=deduped.filter((row)=>row.user_id!==viewerId).sort((a,b)=>{const ranks:Record<EvidenceLevel,number>={exact_variant:1,exact_product:2,product_family:3,similar_garments:4,brand_garment_type:5,category_fit:6};const ar=evidenceLevel(a,metaById.get(a.fit_report_id),product.id,selectedVariationKey);const br=evidenceLevel(b,metaById.get(b.fit_report_id),product.id,selectedVariationKey);return ranks[ar]-ranks[br]||b.historical_match_score-a.historical_match_score||b.historical_coverage_percent-a.historical_coverage_percent;});
  const profiles=(profilesResult.error?[]:(profilesResult.data??[])) as Profile[];const profileById=new Map(profiles.map((row)=>[row.id,row]));const evidenceProducts=(productsResult.error?[]:(productsResult.data??[])) as EvidenceProduct[];const productById=new Map(evidenceProducts.map((row)=>[row.id,row]));const sizes=(sizeResult.data??[]) as SizeRow[];const sizeById=new Map(sizes.map((row)=>[row.id,row]));const safeSizes=buildSafeSizeAdjacency(sizes.map((row):NormalizedSizeDescriptor=>({id:row.id,normalizedKey:row.normalized_key,displayLabel:row.display_label,kind:row.kind,sizingSystem:row.sizing_system,alphaSize:row.alpha_size,numericSize:row.numeric_size,shoeSize:row.shoe_size}))) as Map<string,Adjacency>;const snapshotMatches=((snapshotResult.error?[]:snapshotResult.data)??[]) as SnapshotMatch[];const snapshotByReport=new Map(snapshotMatches.map((row)=>[row.fit_report_id,row]));const attrs=attributeSets(((attributeResult.error?[]:attributeResult.data)??[]) as AttributeRow[]);const sharedDirectional=new Map(deduped.filter((row)=>row.user_id===viewerId).map((row)=>[row.fit_report_id,row.directional_fit_support]));
  const scopedCommunity=selectedVariationKey?community.filter((row)=>row.evidence_product_id!==product.id||metaById.get(row.fit_report_id)?.tracked_variation_key===selectedVariationKey):community;
  const communityEvidence:RecommendationEvidence[]=scopedCommunity.map((row)=>{const size=sizeAdjacency(row.normalized_size_id,row.original_size_label,sizeById,safeSizes);return{sizeKey:size.current.sizeKey,sizeLabel:size.current.sizeLabel,fit:row.fit,matchScore:row.historical_match_score,coveragePercent:row.historical_coverage_percent,evidenceLevel:evidenceLevel(row,metaById.get(row.fit_report_id),product.id,selectedVariationKey),attributeOverlap:row.attribute_overlap,directionalFitSupport:row.directional_fit_support,source:"community",sourceRelevance:1,adjacentSizeUp:size.up,adjacentSizeDown:size.down};});
  const closetEvidence:RecommendationEvidence[]=ownReports.flatMap((report)=>{if(report.garment_condition!=="normal")return[];if(selectedVariationKey&&report.product_id===product.id&&report.tracked_variation_key!==selectedVariationKey)return[];const source=productById.get(report.product_id);const match=snapshotByReport.get(report.id);if(!source||!match)return[];const attributeOverlap=overlap(attrs.get(product.id),attrs.get(source.id));const sameVariation=report.product_id===product.id&&Boolean(selectedVariationKey&&report.tracked_variation_key===selectedVariationKey);const sourceRelevance=closetEvidenceRelevance({sameProduct:report.product_id===product.id,sameVariation,sameBrand:source.brand_id===product.brand_id,sameGarmentType:Boolean(source.garment_type_key&&source.garment_type_key===product.garment_type_key),sameCategory:source.category===product.category,attributeOverlap});if(sourceRelevance<=0)return[];const size=sizeAdjacency(report.normalized_size_id,report.size_label,sizeById,safeSizes);return[{sizeKey:size.current.sizeKey,sizeLabel:size.current.sizeLabel,fit:report.fit,matchScore:match.historical_match_score,coveragePercent:match.historical_coverage_percent,evidenceLevel:closetLevel(report,product,source,selectedVariationKey,attributeOverlap),attributeOverlap,directionalFitSupport:sharedDirectional.get(report.id)??null,source:"closet" as const,sourceRelevance,adjacentSizeUp:size.up,adjacentSizeDown:size.down}];});
  const recommendation=recommendSize([...communityEvidence,...closetEvidence]);const exactCandidates=scopedCommunity.filter((row)=>row.evidence_product_id===product.id&&(!selectedVariationKey||metaById.get(row.fit_report_id)?.tracked_variation_key===selectedVariationKey)).sort((a,b)=>b.historical_match_score-a.historical_match_score||b.historical_coverage_percent-a.historical_coverage_percent);const sizeFor=(row:Candidate)=>sizeAdjacency(row.normalized_size_id,row.original_size_label,sizeById,safeSizes).current.sizeLabel;const strongExact=exactCandidates.filter((row)=>row.historical_match_score>=STRONG_FIT_REPORT_MATCH_THRESHOLD);
  return{recommendation,mixed:Boolean(recommendation?.sourceBreakdown.sourcesAgree===false),exactCandidates,strongGroups:aggregateStrong(strongExact,sizeFor),profileById,sizeFor};
});

function BodyMatchCard({label,row,profileById,sizeFor}:{label:string;row:Candidate;profileById:Map<string,Profile>;sizeFor:(row:Candidate)=>string}){const username=profileById.get(row.user_id)?.username?.trim()||null;return <div className={styles.evidenceCard}><div><span className="eyebrow">{label}</span>{username?<Link className={styles.personLink} href={`/people/${encodeURIComponent(username)}`} prefetch={false}>@{username}</Link>:<strong>Member</strong>}</div><div><MatchPercentageBadge score={row.historical_match_score} compact/><span>Body Match</span></div><div><strong>Size {sizeFor(row)}</strong><span>Fit Result: {FIT_RESULT_LABELS[row.fit]??row.fit}</span></div></div>;}

export function FituitionEvidenceFallback(){return <section className={styles.section} aria-busy="true"><div className={styles.sectionHeader}><span className="eyebrow">FITuition</span><h2>Calculating your fit evidence…</h2></div></section>;}

export async function FituitionEvidenceSections({productId,viewerId,slug,selectedVariationKey,retryHref}:{productId:string;viewerId:string;slug:string;selectedVariationKey:string|null;retryHref:string}){
  let data:FituitionData;try{data=await loadFituitionData(productId,viewerId,selectedVariationKey);}catch{return <section className={styles.section}><div className={styles.sectionHeader}><span className="eyebrow">FITuition</span><h2>Personalized evidence couldn’t finish.</h2><Link href={retryHref} prefetch={false}>Retry FITuition →</Link></div></section>;}
  const {recommendation,mixed,exactCandidates,strongGroups,profileById,sizeFor}=data;
  const closest=exactCandidates[0]??null;
  const recommendedGroup=recommendation?strongGroups.find((group)=>group.size===recommendation.sizeLabel)??null:null;
  const lowMatches=exactCandidates.slice(0,3);
  const strongState=Boolean(recommendation&&recommendedGroup&&closest&&closest.historical_match_score>=STRONG_FIT_REPORT_MATCH_THRESHOLD);
  return <section className={styles.section}>
    {strongState&&recommendation&&recommendedGroup&&closest?<><div className={styles.sectionHeader}><span className="eyebrow">FITuition</span><h2>FITuition recommends: Size {recommendation.sizeLabel}</h2><p><strong>Confidence: {recommendationConfidenceLabel(recommendation.confidence)}</strong> · Based on {recommendation.sizeEvidenceCount} relevant Fit Report{recommendation.sizeEvidenceCount===1?"":"s"}.{mixed?" Evidence is mixed, so confidence reflects that split.":""}</p></div><div className={styles.strongBox}><div className={styles.strongHeader}><strong>Aggregate Fit Report evidence</strong><span>{recommendedGroup.count} strong Body Match{recommendedGroup.count===1?"":"es"} wore Size {recommendedGroup.size}</span></div><div className={styles.aggregateList}>{recommendedGroup.fits.map((fit)=><div className={styles.aggregateRow} key={fit.fit}><strong>{fit.count}</strong><span>{fit.label}</span></div>)}</div></div><BodyMatchCard label="YOUR CLOSEST MATCH" row={closest} profileById={profileById} sizeFor={sizeFor}/></>:<><div className={styles.sectionHeader}><span className="eyebrow">FITuition</span><h2>Not enough evidence yet to confidently recommend a size.</h2><p>{lowMatches.length?"These are the best available Fit Reports for this garment. Lower Body Matches may be less predictive, so FITuition is not forcing a recommendation.":"There are not enough member Fit Reports for this garment yet to make a reliable recommendation."}</p></div>{lowMatches.map((row,index)=><BodyMatchCard key={row.fit_report_id} label={index===0?"BEST AVAILABLE MATCH":"AVAILABLE FIT REPORT"} row={row} profileById={profileById} sizeFor={sizeFor}/>)}</>}
    {!strongState?<GarmentNotifyButton slug={slug} variationKey={selectedVariationKey}/>:null}
  </section>;
}
