"use client";

import { useEffect, useRef, useState } from "react";
import { saveUnifiedProfileSettings, saveUsernameSettings } from "@/app/settings/actions";
import styles from "@/app/settings/settings.module.css";
import { US_STATE_OPTIONS } from "@/lib/profile-location";

const MAX_INPUT_BYTES=8*1024*1024;const MAX_OUTPUT_BYTES=400*1024;const ALLOWED_TYPES=new Set(["image/jpeg","image/png","image/webp"]);
type Drawable=ImageBitmap|HTMLImageElement;type FitCommunity="men"|"women"|"both";type UsernameAvailability="idle"|"checking"|"available"|"taken"|"invalid";
type Props={username:string;displayName:string;bio:string;city:string;stateRegion:string;fitCommunity:FitCommunity;currentPhotoUrl:string|null;fallbackInitial:string;usernameCanChange:boolean;usernameNextChangeAt:string|null};
async function loadImage(file:File):Promise<Drawable>{if("createImageBitmap" in window)return createImageBitmap(file);const url=URL.createObjectURL(file);try{const image=new Image();image.decoding="async";image.src=url;await image.decode();return image;}finally{URL.revokeObjectURL(url);}}
function dimensions(source:Drawable){return source instanceof ImageBitmap?{width:source.width,height:source.height}:{width:source.naturalWidth,height:source.naturalHeight};}
function webpBlob(canvas:HTMLCanvasElement,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob((blob)=>blob?resolve(blob):reject(new Error("Photo conversion failed.")),"image/webp",quality));}
async function optimizeProfilePhoto(source:Drawable){const original=dimensions(source);const side=Math.min(original.width,original.height);const sourceX=Math.max(0,Math.round((original.width-side)/2));const sourceY=Math.max(0,Math.round((original.height-side)/2));for(const size of [512,448,384]){const canvas=document.createElement("canvas");canvas.width=size;canvas.height=size;const context=canvas.getContext("2d",{alpha:false});if(!context)throw new Error("Photo processing is unavailable.");context.drawImage(source,sourceX,sourceY,side,side,0,0,size,size);for(const quality of [.82,.72,.62,.52]){const blob=await webpBlob(canvas,quality);if(blob.size<=MAX_OUTPUT_BYTES)return blob;}}throw new Error("This photo could not be reduced enough. Try a different photo.");}
function assign(input:HTMLInputElement|null,blob:Blob){if(!input)return;const transfer=new DataTransfer();transfer.items.add(new File([blob],"profile.webp",{type:"image/webp"}));input.files=transfer.files;}
function dateLabel(value:string|null){if(!value)return null;return new Intl.DateTimeFormat("en-US",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value));}

export function ProfileSettingsForm({username,displayName,bio,city,stateRegion,fitCommunity,currentPhotoUrl,fallbackInitial,usernameCanChange,usernameNextChangeAt}:Props){
  const optimizedRef=useRef<HTMLInputElement>(null);const previewObjectUrl=useRef<string|null>(null);
  const [editing,setEditing]=useState(false);const [displayNameValue,setDisplayNameValue]=useState(displayName);const [bioValue,setBioValue]=useState(bio);const [cityValue,setCityValue]=useState(city);const [stateValue,setStateValue]=useState(stateRegion);const [communityValue,setCommunityValue]=useState<FitCommunity>(fitCommunity);const [preview,setPreview]=useState(currentPhotoUrl);const [removePhoto,setRemovePhoto]=useState(false);const [photoStatus,setPhotoStatus]=useState<string|null>(null);const [photoBusy,setPhotoBusy]=useState(false);
  const [usernameEditing,setUsernameEditing]=useState(false);const [usernameValue,setUsernameValue]=useState(username);const [availability,setAvailability]=useState<UsernameAvailability>("idle");

  useEffect(()=>{if(!usernameEditing||usernameValue===username){setAvailability("idle");return;}if(!/^[A-Za-z0-9_]{3,32}$/.test(usernameValue)){setAvailability("invalid");return;}setAvailability("checking");const controller=new AbortController();const timer=window.setTimeout(()=>{void fetch(`/api/settings/username-availability?username=${encodeURIComponent(usernameValue)}`,{signal:controller.signal,cache:"no-store"}).then(async(response)=>{if(!response.ok)throw new Error();const payload=await response.json() as {available?:boolean;canChange?:boolean};setAvailability(payload.available&&payload.canChange?"available":"taken");}).catch((error)=>{if(error?.name!=="AbortError")setAvailability("idle");});},300);return()=>{window.clearTimeout(timer);controller.abort();};},[usernameEditing,usernameValue,username]);

  function clearPreparedPhoto(){if(optimizedRef.current)optimizedRef.current.value="";if(previewObjectUrl.current){URL.revokeObjectURL(previewObjectUrl.current);previewObjectUrl.current=null;}}
  function cancelEditing(){clearPreparedPhoto();setDisplayNameValue(displayName);setBioValue(bio);setCityValue(city);setStateValue(stateRegion);setCommunityValue(fitCommunity);setPreview(currentPhotoUrl);setRemovePhoto(false);setPhotoStatus(null);setEditing(false);}
  function cancelUsername(){setUsernameValue(username);setAvailability("idle");setUsernameEditing(false);}
  async function preparePhoto(file:File|undefined){clearPreparedPhoto();if(!file){setPreview(removePhoto?null:currentPhotoUrl);setPhotoStatus(null);return;}setPhotoBusy(true);try{if(!ALLOWED_TYPES.has(file.type)||file.size>MAX_INPUT_BYTES)throw new Error("Choose a JPEG, PNG, or WebP photo no larger than 8 MB.");const source=await loadImage(file);try{const blob=await optimizeProfilePhoto(source);assign(optimizedRef.current,blob);previewObjectUrl.current=URL.createObjectURL(blob);setPreview(previewObjectUrl.current);setRemovePhoto(false);setPhotoStatus("New photo ready");}finally{if(source instanceof ImageBitmap)source.close();}}catch(error){setPhotoStatus(error instanceof Error?error.message:"Photo could not be prepared.");}finally{setPhotoBusy(false);}}
  function markPhotoForRemoval(){clearPreparedPhoto();setPreview(null);setRemovePhoto(true);setPhotoStatus("Photo will be removed when you save.");}
  const nextUsernameDate=dateLabel(usernameNextChangeAt);const usernameChanged=usernameValue!==username;

  return <div className={styles.profileCard}>
    <form id="profileEditorForm" action={saveUnifiedProfileSettings}/>
    <div className={styles.cardHeader}><div><span className={styles.sectionKicker}>PROFILE</span><h2>Edit My Profile</h2></div>{!editing?<button type="button" className={styles.editButton} onClick={()=>setEditing(true)}>Edit Profile</button>:null}</div>
    <div className={styles.profileTop}>
      <div className={styles.avatar}>{preview?<img src={preview} alt="Your profile"/>:<span>{fallbackInitial}</span>}</div>
      <div className={styles.photoArea}><strong>Profile photo</strong><span className={styles.helpText}>Visible on your LikeSized profile.</span>{editing?<div className={styles.photoActions}><label className={styles.fileButton}>Change photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={photoBusy} onChange={(event)=>preparePhoto(event.currentTarget.files?.[0])}/></label>{(currentPhotoUrl||preview)&&!removePhoto?<button type="button" className={styles.textButton} onClick={markPhotoForRemoval}>Remove</button>:null}</div>:null}{editing&&photoStatus?<span className={styles.photoStatus} aria-live="polite">{photoStatus}</span>:null}</div>
      <input ref={optimizedRef} form="profileEditorForm" name="profile_photo" type="file" accept="image/webp" hidden readOnly/><input form="profileEditorForm" name="remove_profile_photo" type="hidden" value={removePhoto?"1":"0"}/>
    </div>

    <div className={styles.profileGrid}>
      <div className={styles.usernameBlock}>
        <div className={styles.fieldLabelRow}><span>Username</span>{!usernameEditing?<button type="button" className={styles.inlineAction} disabled={!usernameCanChange} onClick={()=>setUsernameEditing(true)}>Change username</button>:null}</div>
        {!usernameEditing?<div className={styles.readOnlyValue}>@{username}</div>:<form className={styles.usernameForm} action={saveUsernameSettings}><div className={styles.usernameInputWrap}><span>@</span><input name="username" value={usernameValue} onChange={(event)=>setUsernameValue(event.target.value)} minLength={3} maxLength={32} pattern="[A-Za-z0-9_]{3,32}" autoCapitalize="none" autoCorrect="off" spellCheck={false} required autoFocus/></div><div className={styles.usernameRules}>3–32 characters · letters, numbers, and underscores only · must be unique · can be changed once every 30 days. Your previous username stays reserved to you for 30 days.</div><div className={styles.usernameStatus} aria-live="polite">{availability==="checking"?"Checking availability…":availability==="available"?"✓ Username available":availability==="taken"?"That username is not available.":availability==="invalid"?"Use 3–32 letters, numbers, or underscores.":null}</div><div className={styles.usernameActions}><button type="submit" className={styles.saveButton} disabled={!usernameChanged||availability!=="available"}>Save username</button><button type="button" className={styles.cancelButton} onClick={cancelUsername}>Cancel</button></div></form>}
        {!usernameCanChange&&nextUsernameDate?<small className={styles.cooldownText}>You can change your username again on {nextUsernameDate}.</small>:null}
      </div>

      <label className={styles.field}><span>Display name</span><input form="profileEditorForm" name="display_name" value={displayNameValue} onChange={(event)=>setDisplayNameValue(event.target.value)} maxLength={80} readOnly={!editing} aria-readonly={!editing}/></label>
      <label className={`${styles.field} ${styles.fullField}`}><span>Bio</span><textarea form="profileEditorForm" name="bio" value={bioValue} onChange={(event)=>setBioValue(event.target.value)} maxLength={300} rows={3} readOnly={!editing} aria-readonly={!editing}/>{editing?<small>{bioValue.length} / 300</small>:null}</label>
      <label className={styles.field}><span>City</span><input form="profileEditorForm" name="city" value={cityValue} onChange={(event)=>setCityValue(event.target.value)} maxLength={80} autoComplete="address-level2" readOnly={!editing} aria-readonly={!editing} required/></label>
      <label className={styles.field}><span>State</span><select form="profileEditorForm" name="state_region" value={stateValue} onChange={(event)=>setStateValue(event.target.value)} disabled={!editing} required><option value="" disabled>Select state</option>{US_STATE_OPTIONS.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select>{!editing?<input form="profileEditorForm" type="hidden" name="state_region" value={stateValue}/>:null}</label>
      <div className={`${styles.helpText} ${styles.fullField}`}>City and state stay private.</div>
      <label className={styles.field}><span>Fit Community</span><select form="profileEditorForm" name="fit_community" value={communityValue} onChange={(event)=>setCommunityValue(event.target.value as FitCommunity)} disabled={!editing} required><option value="men">Men</option><option value="women">Women</option><option value="both">Both</option></select>{!editing?<input form="profileEditorForm" type="hidden" name="fit_community" value={communityValue}/>:null}</label>
    </div>
    {editing?<div className={styles.formActions}><button form="profileEditorForm" type="submit" className={styles.saveButton} disabled={photoBusy}>Save Changes</button><button type="button" className={styles.cancelButton} onClick={cancelEditing}>Cancel</button></div>:null}
  </div>;
}
