"use client";

import { type ReactNode, useEffect, useState } from "react";
import { GARMENT_CATEGORIES, GARMENT_TYPES, questionsForGarmentType } from "@/lib/garment-taxonomy";

type Brand={id:string;name:string}; type Product={id:string;name:string;brand_name:string;garment_type_key:string|null;manufacturer_style_number:string|null};
type External={id:string;provider:string;externalProductId:string;brand:string;itemName:string;sourceUrl:string|null;imageUrl:string|null;styleId:string|null;sourceName:string|null;sourceRecord:Record<string,unknown>};

export function CatalogGarmentFields({brands,children}:{brands:Brand[];products:Product[];children:ReactNode}){
  const [step,setStep]=useState<"find"|"details">("find"),[query,setQuery]=useState(""),[brand,setBrand]=useState(""),[itemName,setItemName]=useState(""),[type,setType]=useState(""),[style,setStyle]=useState(""),[existing,setExisting]=useState(""),[confirmation,setConfirmation]=useState<""|"confirm"|"change"|"unsure">("");
  const [local,setLocal]=useState<Product[]>([]),[online,setOnline]=useState<External[]>([]),[error,setError]=useState(""),[retailSearch,setRetailSearch]=useState(false),[sourceUrl,setSourceUrl]=useState(""),[provider,setProvider]=useState(""),[record,setRecord]=useState(""),[answers,setAnswers]=useState<Record<string,string>>({});
  const selectedType=GARMENT_TYPES.find((item)=>item.key===type);
  const questions=questionsForGarmentType(type).filter((item)=>item.key!=="neckline_height"||(answers.top_sleeve!=="strapless"&&answers.swim_top!=="strapless"));
  useEffect(()=>{
    if(step!=="find"||query.trim().length<3){setLocal([]);setOnline([]);setError("");return;}
    const controller=new AbortController(),timer=window.setTimeout(async()=>{
      try { const response=await fetch(`/api/catalog/search?q=${encodeURIComponent(query)}${retailSearch?"&retail=1":""}`,{signal:controller.signal}); const body=await response.json() as {local?:Product[];external?:External[];error?:string};
        if(!response.ok){setLocal([]);setOnline([]);setError(body.error??"Item search could not load right now. Please try again.");return;}
        setLocal(body.local??[]);setOnline(body.external??[]);setError("");
      } catch(e){if((e as Error).name!=="AbortError")setError("Item search could not load right now. Please try again.");}
    },350); return()=>{clearTimeout(timer);controller.abort();};
  },[step,query,retailSearch]);
  function clearSource(){setExisting("");setConfirmation("");setSourceUrl("");setProvider("");setRecord("");}
  function chooseLocal(item:Product){clearSource();setExisting(item.id);setBrand(item.brand_name);setItemName(item.name);setType(item.garment_type_key??"");setStyle(item.manufacturer_style_number??"");setAnswers({});setStep("details");}
  function chooseOnline(item:External){clearSource();setBrand(item.brand);setItemName(item.itemName);setStyle(item.styleId??"");setSourceUrl(item.sourceUrl??"");setProvider(item.provider);setRecord(JSON.stringify({externalProductId:item.externalProductId,sourceRecord:item.sourceRecord,imageUrl:item.imageUrl}));setAnswers({});setStep("details");}
  function chooseManual(){clearSource();setBrand("");setItemName("");setType("");setStyle("");setAnswers({});setStep("details");}
  function reset(){clearSource();setQuery("");setLocal([]);setOnline([]);setStep("find");}
  if(step==="find")return <section className="fitDimensionFields"><label>Find your item<input autoFocus value={query} onChange={(e)=>{setQuery(e.target.value);setRetailSearch(false);}} placeholder="Search brand, item name, Style ID, or barcode"/><span className="fieldHelp">We check LikeSized first. If yours is not here, you can search the retail catalog.</span></label>{query.trim().length>=3?<div className="catalogSuggestionList">{local.map((item)=><button className="catalogSuggestion" type="button" onClick={()=>chooseLocal(item)} key={item.id}><span><b>{item.brand_name} · {item.name}</b><small>Already in LikeSized</small></span></button>)}{online.map((item)=><button className="catalogSuggestion" type="button" onClick={()=>chooseOnline(item)} key={item.id}>{item.imageUrl?<img src={item.imageUrl} alt=""/>:null}<span><b>{item.brand?item.brand+" · ":""}{item.itemName}</b><small>{item.sourceName??"Retail catalog"}</small></span></button>)}</div>:null}{query.trim().length>=3&&!retailSearch?<button className="secondaryButton" type="button" onClick={()=>setRetailSearch(true)}>Search retail catalog for “{query.trim()}”</button>:null}{error?<p className="fieldHelp" role="status">{error}</p>:null}<button className="secondaryButton" type="button" onClick={chooseManual}>Enter item manually</button></section>;
  return <><input type="hidden" name="existing_product_id" value={existing}/><input type="hidden" name="catalog_confirmation" value={confirmation}/><input type="hidden" name="catalog_source_url" value={sourceUrl}/><input type="hidden" name="catalog_source_provider" value={provider}/><input type="hidden" name="catalog_source_record" value={record}/>
    <section className="fitDimensionFields"><button className="secondaryButton" type="button" onClick={reset}>← Find a different item</button><div className="fieldPair"><label>Brand<input name="brand" list="brand-options" maxLength={120} value={brand} onChange={(e)=>{clearSource();setBrand(e.target.value);}} required/><datalist id="brand-options">{brands.map((item)=><option value={item.name} key={item.id}/>)}</datalist></label><label>Item name<input name="product" maxLength={180} value={itemName} onChange={(e)=>{clearSource();setItemName(e.target.value);}} required/></label></div>
    {existing?<fieldset className="fitDimensionFields"><legend>Are the saved item details correct?</legend><div className="fieldPair"><label><input type="radio" checked={confirmation==="confirm"} onChange={()=>setConfirmation("confirm")}/> Yes, they’re correct</label><label><input type="radio" checked={confirmation==="change"} onChange={()=>setConfirmation("change")}/> I need to change something</label><label><input type="radio" checked={confirmation==="unsure"} onChange={()=>setConfirmation("unsure")}/> Not sure</label></div></fieldset>:null}
    <label>Garment type<select name="garment_type" value={type} onChange={(e)=>{clearSource();setType(e.target.value);setAnswers({});}} required><option value="" disabled>Select the specific garment</option>{GARMENT_CATEGORIES.map((category)=><optgroup key={category.value} label={category.label}>{GARMENT_TYPES.filter((item)=>item.category===category.value).map((item)=><option value={item.key} key={item.key}>{item.label}</option>)}</optgroup>)}</select>{selectedType?<span className="fieldHelp">LikeSized files this under {GARMENT_CATEGORIES.find((item)=>item.value===selectedType.category)?.label} automatically.</span>:null}</label>
    {type&&(!existing||confirmation==="change")?<fieldset className="fitDimensionFields"><legend>Optional item details</legend><p className="fieldHelp">Choose only what you know. “Not sure” records no claim.</p><div className="fieldPair">{questions.map((item)=><label key={item.key}>{item.label}<select name={`product_attribute__${item.key}`} value={answers[item.key]??""} onChange={(e)=>{const value=e.target.value;setAnswers((current)=>{const next={...current,[item.key]:value};if((item.key==="top_sleeve"||item.key==="swim_top")&&value==="strapless")delete next.neckline_height;return next;});}}><option value="">Not sure</option>{item.options.map((option)=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label>)}</div></fieldset>:null}
    <label>Manufacturer Style ID <span className="muted inlineMuted">optional</span><input name="style_number" maxLength={100} value={style} onChange={(e)=>{clearSource();setStyle(e.target.value);}}/></label></section>{children}</>;
}
