"use client";

import { createContext, type ReactNode, useContext, useEffect, useRef, useState } from "react";
import { COLOR_FAMILIES, GARMENT_CATEGORIES, GARMENT_TYPES, questionsForGarmentType } from "@/lib/garment-taxonomy";

type Brand={id:string;name:string}; type Product={id:string;name:string;brand_name:string;garment_type_key:string|null;manufacturer_style_number:string|null};
type External={id:string;provider:string;externalProductId:string;brand:string;itemName:string;sourceUrl:string|null;imageUrl:string|null;styleId:string|null;sourceName:string|null;sourceRecord:Record<string,unknown>};
type IntakeMode={retailImport:boolean;hasImportedColors:boolean};
const IntakeModeContext=createContext<IntakeMode>({retailImport:false,hasImportedColors:false});
function itemNameWithoutBrand(brand:string,itemName:string){
  const normalizedBrand=brand.trim().replace(/[.*+?^${}()|[\]\\]/g,"\\$&");
  return normalizedBrand?itemName.replace(new RegExp(`^${normalizedBrand}\\s*[·:|—-]?\\s*`,"i"),"").trim()||itemName:itemName;
}
function sourceHasColors(value:unknown):boolean{
  if(Array.isArray(value))return value.some(sourceHasColors);
  if(!value||typeof value!=="object")return false;
  return Object.entries(value as Record<string,unknown>).some(([key,child])=>/color|colour|swatch|shade|wash/i.test(key)?(typeof child==="string"&&child.trim().length>0||Array.isArray(child)&&child.length>0):sourceHasColors(child));
}
function sourceWords(value:unknown,words:string[]=[]):string[]{
  if(typeof value==="string"){if(value.length<500)words.push(value);return words;}
  if(Array.isArray(value)){value.forEach((child)=>sourceWords(child,words));return words;}
  if(value&&typeof value==="object")Object.values(value as Record<string,unknown>).forEach((child)=>sourceWords(child,words));
  return words;
}
function inferredGarmentType(item:External){
  const text=sourceWords(item.sourceRecord,[item.itemName]).join(" ").toLowerCase();
  const matches:[string,RegExp][]=[["dress_shirt",/dress shirt/],["casual_button_down",/button.?down/],["flannel_shirt",/flannel/],["strapless_top",/strapless|tube top|bandeau top/],["halter_top",/halter/],["tankini_top",/tankini/],["bikini_bottom",/bikini bottom/],["bikini_top",/bikini top/],["one_piece_swimsuit",/one.?piece swimsuit|one.?piece swim/],["swim_trunks",/swim trunk/],["board_shorts",/board short/],["sports_bra",/sports bra/],["bralette",/bralette/],["bra",/\bbra\b/],["jacket_coat",/jacket|coat|parka|puffer|trench/],["cardigan",/cardigan/],["sweatshirt",/sweatshirt/],["hoodie",/hoodie/],["sweater",/sweater|pullover|knit top/],["t_shirt",/t.?shirt|tee\b/],["polo",/polo/],["blouse",/blouse/],["camisole",/camisole|cami\b/],["tank",/tank top/],["jeans",/jeans|denim/],["cargo_pants",/cargo pants?/],["sweatpants",/sweatpants|sweat pants/],["joggers",/joggers?/],["leggings",/leggings?/],["shorts",/shorts?/],["skirt",/skirt/],["dress",/\bdress\b/],["jumpsuit",/jumpsuit/],["romper",/romper/],["bodysuit",/bodysuit/],["overalls",/overalls?/],["sneakers",/sneakers?|trainers?/],["boots",/boots?/],["sandals",/sandals?/],["heels",/heels?|pumps?/],["loafers",/loafers?/],["flats",/flats?/]];
  return matches.find(([,pattern])=>pattern.test(text))?.[0]??"";
}
function inferredAnswers(type:string,item:External){
  const text=sourceWords(item.sourceRecord,[item.itemName]).join(" ").toLowerCase(); const answers:Record<string,string>={};
  for(const question of questionsForGarmentType(type)){
    const option=question.options.find((candidate)=>candidate.value!=="regular"&&candidate.value!=="no"&&new RegExp(`\\b${candidate.label.toLowerCase().replace(/[.*+?^${}()|[\]\\]/g,"\\$&").replace(/\\s+/g,"\\s+")}\\b`).test(text));
    if(option)answers[question.key]=option.value;
  }
  return answers;
}

export function CatalogColorField(){const {retailImport,hasImportedColors}=useContext(IntakeModeContext);return !retailImport||!hasImportedColors?<label>Color<select name="color_family" defaultValue="" required><option value="" disabled>Select a color</option>{COLOR_FAMILIES.map((item)=><option value={item.value} key={item.value}>{item.label}</option>)}</select></label>:<input type="hidden" name="color_family" value=""/>;}
export function CatalogManualIdentifiers(){const {retailImport}=useContext(IntakeModeContext);return retailImport?null:<div className="fieldPair"><label>Product link <span className="muted inlineMuted">optional</span><input name="product_url" type="url" maxLength={1000} placeholder="https://..." /></label><label>Barcode / SKU <span className="muted inlineMuted">optional</span><input name="identifier" maxLength={120} placeholder="Scan or enter if available" /></label></div>;}

export function CatalogGarmentFields({brands,children}:{brands:Brand[];products:Product[];children:ReactNode}){
  const [step,setStep]=useState<"find"|"details">("find"),[query,setQuery]=useState(""),[brand,setBrand]=useState(""),[itemName,setItemName]=useState(""),[type,setType]=useState(""),[style,setStyle]=useState(""),[existing,setExisting]=useState(""),[confirmation,setConfirmation]=useState<""|"confirm"|"change"|"unsure">("");
  const [local,setLocal]=useState<Product[]>([]),[online,setOnline]=useState<External[]>([]),[error,setError]=useState(""),[retailSearch,setRetailSearch]=useState(false),[findMode,setFindMode]=useState<"barcode"|"likesized"|"retail">("likesized"),[sourceUrl,setSourceUrl]=useState(""),[provider,setProvider]=useState(""),[record,setRecord]=useState(""),[selectedImage,setSelectedImage]=useState(""),[hasImportedColors,setHasImportedColors]=useState(false),[sourceTags,setSourceTags]=useState<string[]>([]),[answers,setAnswers]=useState<Record<string,string>>({});
  const scannerVideo=useRef<HTMLVideoElement>(null),scannerControls=useRef<{stop:()=>void}|null>(null);
  const selectedType=GARMENT_TYPES.find((item)=>item.key===type);
  const questions=questionsForGarmentType(type).filter((item)=>item.key!=="neckline_height"||(answers.top_sleeve!=="strapless"&&answers.swim_top!=="strapless"));
  useEffect(()=>{
    if(step!=="find"||query.trim().length<3){setLocal([]);setOnline([]);setError("");return;}
    const controller=new AbortController(),timer=window.setTimeout(async()=>{
      try { const response=await fetch(`/api/catalog/search?q=${encodeURIComponent(query)}${retailSearch?"&retail=1":""}`,{signal:controller.signal}); const body=await response.json() as {local?:Product[];external?:External[];error?:string};
        if(!response.ok){setLocal([]);setOnline([]);setError(body.error??"Item search could not load right now. Please try again.");return;}
        setLocal(body.local??[]);setOnline(body.external??[]);setError("");
      } catch(e){if((e as Error).name!=="AbortError")setError("Item search could not load right now. Please try again.");}
    },350); return()=>{clearTimeout(timer);controller.abort();};
  },[step,query,retailSearch]);
  function stopScanner(){scannerControls.current?.stop();scannerControls.current=null;}
  useEffect(()=>()=>stopScanner(),[]);
  async function startScanner(){try{stopScanner();const video=scannerVideo.current;if(!video)throw new Error("Scanner is not ready");const {BrowserMultiFormatReader}=await import("@zxing/browser");const reader=new BrowserMultiFormatReader();scannerControls.current=await reader.decodeFromConstraints({video:{facingMode:{ideal:"environment"}}},video,(result)=>{const code=result?.getText().replace(/\D/g,"");if(code){stopScanner();setQuery(code);setRetailSearch(true);}});}catch{setError("Camera access was not available. Type the UPC below instead.");}}
  useEffect(()=>{if(step!=="find"||findMode!=="barcode")return;const timer=window.setTimeout(()=>void startScanner(),50);return()=>{clearTimeout(timer);stopScanner();};},[step,findMode]);
  function clearSource(){setExisting("");setConfirmation("");setSourceUrl("");setProvider("");setRecord("");setHasImportedColors(false);setSourceTags([]);}
  function chooseLocal(item:Product){clearSource();setSelectedImage("");setExisting(item.id);setBrand(item.brand_name);setItemName(item.name);setType(item.garment_type_key??"");setStyle(item.manufacturer_style_number??"");setAnswers({});setStep("details");}
  function chooseOnline(item:External){const detectedType=inferredGarmentType(item);clearSource();setSelectedImage(item.imageUrl??"");setBrand(item.brand);setItemName(itemNameWithoutBrand(item.brand,item.itemName));setType(detectedType);setStyle(item.styleId??"");setSourceUrl(item.sourceUrl??"");setProvider(item.provider);setRecord(JSON.stringify({externalProductId:item.externalProductId,sourceRecord:item.sourceRecord,imageUrl:item.imageUrl}));setHasImportedColors(sourceHasColors(item.sourceRecord));setSourceTags(sourceWords(item.sourceRecord).filter((tag)=>tag.length>1&&tag.length<80).slice(0,12));setAnswers(inferredAnswers(detectedType,item));setStep("details");}
  function chooseManual(){clearSource();setSelectedImage("");setBrand("");setItemName("");setType("");setStyle("");setAnswers({});setStep("details");}
  function reset(){stopScanner();clearSource();setSelectedImage("");setQuery("");setLocal([]);setOnline([]);setFindMode("likesized");setStep("find");}
  if(step==="find")return <section className="fitDimensionFields">
    {findMode==="barcode"?<><button className="catalogBackButton" type="button" onClick={()=>{stopScanner();setFindMode("likesized");setQuery("");setLocal([]);setOnline([]);}}>← Search LikeSized instead</button><p className="fieldHelp">LikeSized checks the scanned UPC first, then imports a retail match when needed.</p><video className="barcodeScanner" ref={scannerVideo} muted playsInline/><label>UPC / barcode<input autoFocus value={query} inputMode="numeric" onChange={(e)=>{setQuery(e.target.value);setRetailSearch(true);}} placeholder="Scan or type barcode"/><span className="fieldHelp">Type it if your camera is unavailable.</span></label><button className="catalogManualButton" type="button" onClick={chooseManual}>Enter item manually</button></>:<><label>Find your item<input autoFocus value={query} onChange={(e)=>{setQuery(e.target.value);setRetailSearch(false);}} placeholder="Search LikeSized by brand, item name, Style ID, or barcode"/><span className="fieldHelp">Search LikeSized first.</span></label><div className="catalogSearchActions"><button className="catalogSearchButton" type="button" onClick={()=>{setFindMode("barcode");setError("");}}>Scan barcode</button><button className="catalogManualButton" type="button" onClick={chooseManual}>Enter item manually</button></div></>}
    {query.trim().length>=3?<div className="catalogSuggestionList">{local.map((item)=><button className="catalogSuggestion" type="button" onClick={()=>chooseLocal(item)} key={item.id}><span><b>{item.brand_name} · {item.name}</b><small>Already in LikeSized</small></span></button>)}{online.map((item)=><button className="catalogSuggestion" type="button" onClick={()=>chooseOnline(item)} key={item.id}>{item.imageUrl?<img src={item.imageUrl} alt=""/>:null}<span><b>{item.brand?item.brand+" · ":""}{item.itemName}</b><small>{item.sourceName??"Retail catalog"}</small></span></button>)}</div>:null}
    {findMode==="likesized"&&query.trim().length>=3&&local.length===0?<div className="catalogSearchActions"><button className="catalogSearchButton" type="button" onClick={()=>{setFindMode("retail");setRetailSearch(true);}}>Can’t find the exact item? Search retail catalog</button></div>:null}{error?<p className="fieldHelp" role="status">{error}</p>:null}</section>;
  return <><input type="hidden" name="existing_product_id" value={existing}/><input type="hidden" name="catalog_confirmation" value={confirmation}/><input type="hidden" name="catalog_source_url" value={sourceUrl}/><input type="hidden" name="catalog_source_provider" value={provider}/><input type="hidden" name="catalog_source_record" value={record}/>
    <section className="fitDimensionFields"><button className="catalogBackButton" type="button" onClick={reset}>← Find a different item</button>{itemName?<div className="catalogSelectedItem">{selectedImage?<img src={selectedImage} alt=""/>:null}<span><small>{provider?"Imported from retail catalog":"Selected item"}</small><b>{brand?brand+" · ":""}{itemName}</b>{provider?<small>{sourceTags.length?`Imported details: ${sourceTags.join(" · ")}`:"The retail record was saved with this item."}</small>:null}</span></div>:null}{provider?<><input type="hidden" name="brand" value={brand}/><input type="hidden" name="product" value={itemName}/></>:<div className="fieldPair"><label>Brand<input name="brand" list="brand-options" maxLength={120} value={brand} onChange={(e)=>{clearSource();setSelectedImage("");setBrand(e.target.value);}} required/><datalist id="brand-options">{brands.map((item)=><option value={item.name} key={item.id}/>)}</datalist></label><label>Item name<input name="product" maxLength={180} value={itemName} onChange={(e)=>{clearSource();setSelectedImage("");setItemName(e.target.value);}} required/></label></div>}
    {existing?<fieldset className="fitDimensionFields"><legend>Are the saved item details correct?</legend><div className="fieldPair"><label><input type="radio" checked={confirmation==="confirm"} onChange={()=>setConfirmation("confirm")}/> Yes, they’re correct</label><label><input type="radio" checked={confirmation==="change"} onChange={()=>setConfirmation("change")}/> I need to change something</label><label><input type="radio" checked={confirmation==="unsure"} onChange={()=>setConfirmation("unsure")}/> Not sure</label></div></fieldset>:null}
    {provider&&type?<><input type="hidden" name="garment_type" value={type}/>{Object.entries(answers).map(([key,value])=><input type="hidden" name={`product_attribute__${key}`} value={value} key={key}/>)}</>:<label>Garment type<select name="garment_type" value={type} onChange={(e)=>{clearSource();setType(e.target.value);setAnswers({});}} required><option value="" disabled>Select the specific garment</option>{GARMENT_CATEGORIES.map((category)=><optgroup key={category.value} label={category.label}>{GARMENT_TYPES.filter((item)=>item.category===category.value).map((item)=><option value={item.key} key={item.key}>{item.label}</option>)}</optgroup>)}</select>{selectedType?<span className="fieldHelp">LikeSized files this under {GARMENT_CATEGORIES.find((item)=>item.value===selectedType.category)?.label} automatically.</span>:null}</label>}
    {provider&&!type?<p className="fieldHelp">This retailer did not identify a specific garment type, so this item cannot be imported yet.</p>:null}
    {type&&!provider&&(!existing||confirmation==="change")?<fieldset className="fitDimensionFields"><legend>Optional item details</legend><p className="fieldHelp">Choose only what you know. “Not sure” records no claim.</p><div className="fieldPair">{questions.map((item)=><label key={item.key}>{item.label}<select name={`product_attribute__${item.key}`} value={answers[item.key]??""} onChange={(e)=>{const value=e.target.value;setAnswers((current)=>{const next={...current,[item.key]:value};if((item.key==="top_sleeve"||item.key==="swim_top")&&value==="strapless")delete next.neckline_height;return next;});}}><option value="">Not sure</option>{item.options.map((option)=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label>)}</div></fieldset>:null}
    {provider?<input type="hidden" name="style_number" value={style}/>:<label>Manufacturer Style ID <span className="muted inlineMuted">optional</span><input name="style_number" maxLength={100} value={style} onChange={(e)=>{clearSource();setStyle(e.target.value);}}/></label>}</section><IntakeModeContext.Provider value={{retailImport:Boolean(provider),hasImportedColors}}>{children}</IntakeModeContext.Provider></>;
}
