-- Isolated cache for owner-approved SerpAPI discovery benchmarking.
-- This cache stores raw external discovery responses only. It does not create,
-- update, merge, or otherwise determine canonical Product identity.

create table if not exists private.serpapi_discovery_cache (
  id bigint generated by default as identity primary key,
  engine text not null default 'google_shopping',
  query_text text not null,
  normalized_query text not null,
  benchmark_group text,
  expected_brand text,
  expected_model text,
  expected_garment_type text,
  search_id text,
  result_count integer not null default 0 check (result_count >= 0),
  raw_response jsonb not null,
  fetched_at timestamptz not null default now(),
  last_reused_at timestamptz not null default now(),
  unique (engine, normalized_query)
);

create index if not exists serpapi_discovery_cache_group_idx
  on private.serpapi_discovery_cache (benchmark_group, fetched_at desc);

comment on table private.serpapi_discovery_cache is
  'Private reusable SerpAPI discovery cache. Raw search output is evidence/candidate data only and must never directly define canonical Product identity.';
