-- Controlled Fit Report vocabulary shared by intake and Explore.

create table public.color_families (
  key text primary key check (key ~ '^[a-z0-9_]+$'),
  label text not null unique,
  sort_order integer not null
);
insert into public.color_families(key,label,sort_order) values
('black','Black',10),
('white','White',20),
('gray','Gray',30),
('silver','Silver',40),
('brown','Brown',50),
('tan_beige','Tan / Beige',60),
('cream_ivory','Cream / Ivory',70),
('red','Red',80),
('orange','Orange',90),
('yellow','Yellow',100),
('green','Green',110),
('blue','Blue',120),
('purple','Purple',130),
('pink','Pink',140),
('gold','Gold',150),
('multicolor','Multicolor',160);
alter table public.color_families enable row level security;
create policy "color families readable" on public.color_families for select to anon,authenticated using (true);
grant select on public.color_families to anon,authenticated;

alter table public.product_variants add column color_family_key text references public.color_families(key);
create index product_variants_color_family_idx on public.product_variants(color_family_key,product_id);

alter table public.fit_reports add column reported_condition text;
alter table public.fit_reports add constraint fit_reports_reported_condition_check check (reported_condition is null or reported_condition in ('new','used','altered'));
comment on column public.fit_reports.reported_condition is 'Member-facing New, Used, or Altered condition. New/Used continue to use normal sizing evidence; Altered is excluded by the canonical recommendation boundary.';

-- `active` is an established matching-engine compatibility flag. Older umbrella
-- and plural keys still back historical Products and calibrated match rules, so
-- intake visibility must not deactivate or rewrite them.
alter table public.garment_types add column intake_active boolean not null default false;
update public.garment_types set intake_active=false;
insert into public.garment_types(key,label,category,match_profile_key,active,intake_active,sort_order) values
('t_shirt','T-shirt','tops','tops_default',true,true,10),
('polo','Polo','tops','tops_default',true,true,20),
('dress_shirt','Dress shirt','tops','tops_default',true,true,30),
('work_shirt','Work shirt','tops','tops_default',true,true,40),
('casual_button_down','Casual button-down','tops','tops_default',true,true,50),
('flannel_shirt','Flannel shirt','tops','tops_default',true,true,60),
('blouse','Blouse','tops','tops_default',true,true,70),
('tank','Tank top','tops','tops_default',true,true,80),
('camisole','Camisole','tops','tops_default',true,true,90),
('strapless_top','Strapless top','tops','tops_default',true,true,100),
('halter_top','Halter top','tops','tops_default',true,true,110),
('sweater','Sweater','tops','tops_default',true,true,120),
('cardigan','Cardigan','tops','tops_default',true,true,130),
('sweatshirt','Sweatshirt','tops','tops_default',true,true,140),
('hoodie','Hoodie','tops','tops_default',true,true,150),
('jeans','Jeans','bottoms','bottoms_default',true,true,160),
('chinos','Chinos','bottoms','bottoms_default',true,true,170),
('dress_pants','Dress pants','bottoms','bottoms_default',true,true,180),
('trousers','Trousers','bottoms','bottoms_default',true,true,190),
('cargo_pants','Cargo pants','bottoms','bottoms_default',true,true,200),
('shorts','Shorts','bottoms','bottoms_default',true,true,210),
('joggers','Joggers','bottoms','bottoms_default',true,true,220),
('sweatpants','Sweatpants','bottoms','bottoms_default',true,true,230),
('leggings','Leggings','bottoms','bottoms_default',true,true,240),
('skirt','Skirt','bottoms','bottoms_default',true,true,250),
('dress','Dress','dresses','one_piece',true,true,260),
('jumpsuit','Jumpsuit','dresses','one_piece',true,true,270),
('romper','Romper','dresses','one_piece',true,true,280),
('bodysuit','Bodysuit','dresses','one_piece',true,true,290),
('overalls','Overalls','dresses','one_piece',true,true,300),
('coveralls','Coveralls','dresses','one_piece',true,true,310),
('suit_jacket','Suit jacket','outerwear','tops_default',true,true,320),
('blazer','Blazer','outerwear','tops_default',true,true,330),
('jacket_coat','Jacket / coat','outerwear','tops_default',true,true,340),
('vest','Vest','outerwear','tops_default',true,true,350),
('wrap_shawl','Wrap / shawl','outerwear','tops_default',true,true,360),
('one_piece_swimsuit','One-piece swimsuit','swimwear','one_piece',true,true,370),
('bikini_top','Bikini top','swimwear','one_piece',true,true,380),
('bikini_bottom','Bikini bottom','swimwear','one_piece',true,true,390),
('tankini_top','Tankini top','swimwear','one_piece',true,true,400),
('swim_trunks','Swim trunks','swimwear','one_piece',true,true,410),
('board_shorts','Board shorts','swimwear','one_piece',true,true,420),
('bra','Bra','intimates','bra',true,true,430),
('bralette','Bralette','intimates','bra',true,true,440),
('sports_bra','Sports bra','intimates','bra',true,true,450),
('underwear','Underwear','intimates','bra',true,true,460),
('shapewear','Shapewear','intimates','bra',true,true,470),
('sneakers','Sneakers','shoes','shoes',true,true,480),
('boots','Boots','shoes','shoes',true,true,490),
('dress_shoes','Dress shoes','shoes','shoes',true,true,500),
('loafers','Loafers','shoes','shoes',true,true,510),
('flats','Flats','shoes','shoes',true,true,520),
('heels','Heels','shoes','shoes',true,true,530),
('sandals','Sandals','shoes','shoes',true,true,540),
('slides','Slides','shoes','shoes',true,true,550),
('clogs','Clogs','shoes','shoes',true,true,560)
on conflict (key) do update set label=excluded.label,category=excluded.category,intake_active=true,sort_order=excluded.sort_order;

insert into public.garment_attribute_definitions(key,label,category,sort_order) values
('intended_fit','Intended fit',null,10),
('cropped','Cropped',null,20),
('sleeve_length','Sleeve',null,30),
('neckline','Neckline',null,40),
('opening','Opening',null,50),
('shape','Shape',null,60),
('neckline_height','Neckline',null,70),
('neck_opening','Neck / opening',null,80),
('length_profile','Length',null,90),
('closure','Closure',null,100),
('cut','Cut',null,110),
('rise','Rise',null,120),
('pleated','Pleated',null,130),
('leg_opening','Leg opening',null,140),
('leg_shape','Leg shape',null,150),
('skort','Skort',null,160),
('top_sleeve','Top / sleeve',null,170),
('bottom_coverage','Bottom coverage',null,180),
('front','Front',null,190),
('jacket_style','Style',null,200),
('hooded','Hooded',null,210),
('vest_style','Style',null,220),
('swim_top','Top',null,230),
('leg_cut','Leg cut',null,240),
('coverage','Coverage',null,250),
('bikini_top_style','Style',null,260),
('support','Support',null,270),
('underwire','Underwire',null,280),
('skirted','Skirted',null,290),
('liner','Liner',null,300),
('bra_style','Style',null,310),
('padding','Padding',null,320),
('bralette_style','Style',null,330),
('underwear_cut','Cut',null,340),
('shapewear_form','Form',null,350),
('target_area','Target area',null,360),
('compression','Compression',null,370),
('shoe_height','Height',null,380),
('shoe_use','Use',null,390),
('shoe_closure','Closure',null,400),
('boot_style','Style',null,410),
('boot_height','Height',null,420),
('heel_height','Heel',null,430),
('dress_shoe_style','Style',null,440),
('toe_shape','Toe',null,450),
('loafer_style','Style',null,460),
('flat_style','Style',null,470),
('heel_style','Heel style',null,480),
('sandal_style','Style',null,490),
('sole','Sole',null,500),
('clog_back','Back',null,510)
-- Preserve the established broad category scope on shared legacy attributes.
-- The new per-Type allowlist is narrower and must not weaken those guards.
on conflict (key) do update set label=excluded.label,sort_order=excluded.sort_order;

insert into public.garment_attribute_options(attribute_key,option_key,label,sort_order) values
('intended_fit','fitted','Fitted',10),
('intended_fit','regular','Regular',20),
('intended_fit','oversized','Oversized',30),
('cropped','yes','Yes',40),
('cropped','no','No',50),
('sleeve_length','short','Short',60),
('sleeve_length','three_quarter','3/4',70),
('sleeve_length','long','Long',80),
('neckline','crew','Crew',90),
('neckline','v_neck','V-neck',100),
('neckline','scoop','Scoop',110),
('neckline','square','Square',120),
('neckline','turtleneck','Turtleneck',130),
('intended_fit','slim','Slim',140),
('intended_fit','relaxed','Relaxed',150),
('opening','button_placket','Button placket',160),
('opening','quarter_zip','Quarter-zip',170),
('opening','full_zip','Full-zip',180),
('sleeve_length','sleeveless','Sleeveless',190),
('neckline','cowl','Cowl',200),
('neckline','boat','Boat neck',210),
('intended_fit','loose','Loose',220),
('shape','fitted','Fitted',230),
('shape','flowy','Flowy',240),
('neckline_height','high','High',250),
('neckline_height','low','Low',260),
('neck_opening','crew','Crew',270),
('neck_opening','v_neck','V-neck',280),
('neck_opening','turtleneck','Turtleneck',290),
('neck_opening','quarter_zip','Quarter-zip',300),
('neck_opening','full_zip','Full-zip',310),
('length_profile','cropped','Cropped',320),
('length_profile','regular','Regular',330),
('length_profile','long','Long',340),
('closure','open_front','Open-front',350),
('closure','button','Button',360),
('closure','zip','Zip',370),
('closure','tie','Tie',380),
('closure','pullover','Pullover',390),
('closure','quarter_zip','Quarter-zip',400),
('closure','full_zip','Full-zip',410),
('cut','skinny','Skinny',420),
('cut','slim','Slim',430),
('cut','straight','Straight',440),
('cut','relaxed','Relaxed',450),
('cut','wide','Wide',460),
('cut','bootcut','Bootcut',470),
('cut','flare','Flare',480),
('rise','low','Low',490),
('rise','mid','Mid',500),
('rise','high','High',510),
('length_profile','ankle','Ankle',520),
('cut','tapered','Tapered',530),
('pleated','yes','Yes',540),
('pleated','no','No',550),
('length_profile','short','Short',560),
('length_profile','mid','Mid',570),
('length_profile','full','Full',580),
('leg_opening','cuffed','Cuffed',590),
('leg_opening','open','Open',600),
('length_profile','capri','Capri',610),
('length_profile','seven_eighths','7/8',620),
('leg_shape','fitted','Fitted',630),
('leg_shape','bootcut','Bootcut',640),
('leg_shape','flare','Flare',650),
('shape','straight','Straight',660),
('shape','a_line','A-line',670),
('shape','pencil','Pencil',680),
('shape','full','Full',690),
('shape','pleated','Pleated',700),
('shape','wrap','Wrap',710),
('length_profile','mini','Mini',720),
('length_profile','knee','Knee',730),
('length_profile','midi','Midi',740),
('length_profile','maxi','Maxi',750),
('skort','yes','Yes',760),
('skort','no','No',770),
('top_sleeve','strapless','Strapless',780),
('top_sleeve','halter','Halter',790),
('top_sleeve','sleeveless','Sleeveless',800),
('top_sleeve','short','Short',810),
('top_sleeve','three_quarter','3/4',820),
('top_sleeve','long','Long',830),
('leg_shape','slim','Slim',840),
('leg_shape','straight','Straight',850),
('leg_shape','wide','Wide',860),
('bottom_coverage','thong','Thong',870),
('bottom_coverage','brief','Brief',880),
('length_profile','shorts','Shorts',890),
('front','single_breasted','Single-breasted',900),
('front','double_breasted','Double-breasted',910),
('jacket_style','denim','Denim',920),
('jacket_style','leather','Leather',930),
('jacket_style','bomber','Bomber',940),
('jacket_style','puffer','Puffer',950),
('jacket_style','rain','Rain',960),
('jacket_style','utility','Utility',970),
('jacket_style','trench','Trench',980),
('jacket_style','peacoat','Peacoat',990),
('jacket_style','overcoat','Overcoat',1000),
('length_profile','waist','Waist',1010),
('length_profile','hip','Hip',1020),
('length_profile','mid_thigh','Mid-thigh',1030),
('hooded','yes','Yes',1040),
('hooded','no','No',1050),
('vest_style','puffer','Puffer',1060),
('vest_style','tailored','Tailored',1070),
('vest_style','utility','Utility',1080),
('closure','open','Open',1090),
('closure','fastened','Fastened',1100),
('closure','belted','Belted',1110),
('swim_top','strapless','Strapless',1120),
('swim_top','halter','Halter',1130),
('swim_top','straps','Straps',1140),
('leg_cut','low','Low',1150),
('leg_cut','regular','Regular',1160),
('leg_cut','high','High',1170),
('coverage','minimal','Minimal',1180),
('coverage','moderate','Moderate',1190),
('coverage','full','Full',1200),
('bikini_top_style','bandeau','Bandeau',1210),
('bikini_top_style','halter','Halter',1220),
('bikini_top_style','triangle','Triangle',1230),
('bikini_top_style','bra_style','Bra-style',1240),
('support','light','Light',1250),
('support','medium','Medium',1260),
('support','high','High',1270),
('underwire','yes','Yes',1280),
('underwire','no','No',1290),
('skirted','yes','Yes',1300),
('skirted','no','No',1310),
('liner','yes','Yes',1320),
('liner','no','No',1330),
('closure','pull_on','Pull-on',1340),
('closure','drawstring','Drawstring',1350),
('closure','fly','Fly',1360),
('bra_style','t_shirt','T-shirt',1370),
('bra_style','balconette','Balconette',1380),
('bra_style','plunge','Plunge',1390),
('bra_style','push_up','Push-up',1400),
('bra_style','strapless','Strapless',1410),
('bra_style','minimizer','Minimizer',1420),
('padding','none','None',1430),
('padding','light','Light',1440),
('padding','padded','Padded',1450),
('bralette_style','triangle','Triangle',1460),
('bralette_style','standard','Standard',1470),
('bralette_style','longline','Longline',1480),
('padding','yes','Yes',1490),
('padding','no','No',1500),
('closure','hook','Hook',1510),
('underwear_cut','brief','Brief',1520),
('underwear_cut','bikini','Bikini',1530),
('underwear_cut','hipster','Hipster',1540),
('underwear_cut','boyshort','Boyshort',1550),
('underwear_cut','thong','Thong',1560),
('underwear_cut','boxer','Boxer',1570),
('underwear_cut','boxer_brief','Boxer brief',1580),
('underwear_cut','trunk','Trunk',1590),
('shapewear_form','brief','Brief',1600),
('shapewear_form','shorts','Shorts',1610),
('shapewear_form','cami','Cami',1620),
('shapewear_form','bodysuit','Bodysuit',1630),
('target_area','waist','Waist',1640),
('target_area','hips','Hips',1650),
('target_area','thighs','Thighs',1660),
('target_area','full_body','Full body',1670),
('compression','light','Light',1680),
('compression','medium','Medium',1690),
('compression','firm','Firm',1700),
('shoe_height','low','Low',1710),
('shoe_height','mid','Mid',1720),
('shoe_height','high','High',1730),
('shoe_use','casual','Casual',1740),
('shoe_use','running','Running',1750),
('shoe_use','training','Training',1760),
('shoe_use','court','Court',1770),
('shoe_closure','lace','Lace',1780),
('shoe_closure','slip_on','Slip-on',1790),
('shoe_closure','hook_loop','Hook-and-loop',1800),
('boot_style','casual','Casual',1810),
('boot_style','work','Work',1820),
('boot_style','hiking','Hiking',1830),
('boot_style','combat','Combat',1840),
('boot_style','cowboy','Cowboy',1850),
('boot_style','dress','Dress',1860),
('boot_style','rain','Rain',1870),
('boot_style','snow','Snow',1880),
('boot_height','ankle','Ankle',1890),
('boot_height','mid_calf','Mid-calf',1900),
('boot_height','knee','Knee',1910),
('boot_height','over_knee','Over-the-knee',1920),
('heel_height','flat','Flat',1930),
('heel_height','low','Low',1940),
('heel_height','mid','Mid',1950),
('heel_height','high','High',1960),
('shoe_closure','pull_on','Pull-on',1970),
('shoe_closure','zip','Zip',1980),
('dress_shoe_style','oxford','Oxford',1990),
('dress_shoe_style','derby','Derby',2000),
('dress_shoe_style','monk_strap','Monk-strap',2010),
('toe_shape','round','Round',2020),
('toe_shape','pointed','Pointed',2030),
('toe_shape','square','Square',2040),
('loafer_style','penny','Penny',2050),
('loafer_style','tassel','Tassel',2060),
('loafer_style','bit','Bit',2070),
('flat_style','ballet','Ballet',2080),
('flat_style','mary_jane','Mary Jane',2090),
('flat_style','slingback','Slingback',2100),
('heel_style','block','Block',2110),
('heel_style','stiletto','Stiletto',2120),
('heel_style','wedge','Wedge',2130),
('heel_style','kitten','Kitten',2140),
('toe_shape','open','Open',2150),
('sandal_style','flat','Flat',2160),
('sandal_style','heeled','Heeled',2170),
('sandal_style','platform','Platform',2180),
('shoe_closure','ankle_strap','Ankle strap',2190),
('shoe_closure','back_strap','Back strap',2200),
('sole','flat','Flat',2210),
('sole','platform','Platform',2220),
('clog_back','open','Open',2230),
('clog_back','strap','Strap',2240),
('clog_back','closed','Closed',2250)
on conflict (attribute_key,option_key) do update set label=excluded.label,sort_order=excluded.sort_order;

comment on table public.color_families is 'Approved broad color families used for controlled Fit Report intake and strict Explore filtering. Manufacturer color/wash wording remains separate in product_variants.color_label.';
comment on table public.garment_types is 'Garment matching and historical compatibility vocabulary. intake_active marks the approved specific physical Types exposed by intake and Explore; the application derives their broad category and exposes at most four optional type-specific questions.';
